# Generated by Django 5.2.8 on 2025-12-05 08:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0003_auto_20251204_1936'),
        ('users', '0003_add_profile_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorDashboardCache',
            fields=[
                ('director', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='director_dashboard_cache', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('active_programs_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('active_cohorts_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_seats', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('seats_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('seats_pending', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_readiness', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cohorts_at_risk', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('mentors_over_capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('mission_bottlenecks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_overdue_seats', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cache_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'director_dashboard_cache',
                'ordering': ['-cache_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectorCohortHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort_name', models.CharField(max_length=255)),
                ('seats_used_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('readiness_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('completion_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentor_coverage_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('next_milestone', models.JSONField(blank=True, default=dict)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('risk_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='programs.cohort')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'director_cohort_health',
                'ordering': ['-risk_score', '-updated_at'],
                'indexes': [models.Index(fields=['director', 'updated_at'], name='director_co_directo_c520ec_idx'), models.Index(fields=['cohort', 'risk_score'], name='director_co_cohort__4d9b3e_idx')],
                'unique_together': {('director', 'cohort')},
            },
        ),
    ]
