# Generated by Django 5.2.9 on 2025-12-13 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director_dashboard', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directorcohorthealth',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='programs.cohort'),
        ),
        migrations.AddField(
            model_name='directorcohorthealth',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_health_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='directorcohorthealth',
            index=models.Index(fields=['director', 'updated_at'], name='director_co_directo_c520ec_idx'),
        ),
        migrations.AddIndex(
            model_name='directorcohorthealth',
            index=models.Index(fields=['cohort', 'risk_score'], name='director_co_cohort__4d9b3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='directorcohorthealth',
            unique_together={('director', 'cohort')},
        ),
    ]
