version: '3.8'

# Production overrides for docker-compose.prod.yml
# Usage: docker-compose -f docker-compose.prod.yml -f compose.override.prod.yml up

services:
  django:
    environment:
      DEBUG: "False"
      DJANGO_SETTINGS_MODULE: core.settings.production
      ALLOWED_HOSTS: ongoza.cyberhub,www.ongoza.cyberhub,api.ongoza.cyberhub
      LOG_LEVEL: WARNING
      SECURE_SSL_REDIRECT: "True"
      SESSION_COOKIE_SECURE: "True"
      CSRF_COOKIE_SECURE: "True"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  fastapi:
    environment:
      FASTAPI_RELOAD: "False"
      FASTAPI_WORKERS: "8"
      LOG_LEVEL: WARNING
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  nextjs:
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_ENVIRONMENT: production
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    # SSL certificates should be mounted here

  postgres-relational:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  postgres-vector:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G



