# Generated by Django 5.2.9 on 2025-12-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardUpdateQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], db_index=True, default='normal', max_length=10)),
                ('reason', models.CharField(help_text='Event that triggered update: "mission_completed", "habit_logged", etc', max_length=100)),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dashboard_update_queue',
                'ordering': ['-priority', 'queued_at'],
            },
        ),
    ]
