# Generated by Django 5.2.8 on 2025-12-03 16:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_apikey_rate_limit_apikey_owner_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDashboardCache',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dashboard_cache', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('readiness_score', models.DecimalField(decimal_places=2, default=0, help_text='Readiness score 0-100 from TalentScope', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_to_ready_days', models.IntegerField(default=365, help_text='Estimated days to employability', validators=[django.core.validators.MinValueValidator(0)])),
                ('skill_heatmap', models.JSONField(blank=True, default=dict, help_text='Skill scores: {networking: 45, cloud: 22, ...}')),
                ('top_3_gaps', models.JSONField(blank=True, default=list, help_text='Top 3 skill gaps: ["DFIR", "Python", "AWS"]')),
                ('habit_streak_current', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('habit_completion_week', models.DecimalField(decimal_places=2, default=0, help_text='Habit completion percentage for current week', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('goals_active_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('goals_completed_week', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('missions_in_progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('missions_in_review', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('missions_completed_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('next_mission_recommended', models.JSONField(blank=True, default=dict, help_text='{id, title, difficulty, est_hours}')),
                ('portfolio_health_score', models.DecimalField(decimal_places=2, default=0, help_text='Portfolio health score 0-100', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('portfolio_items_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('portfolio_items_approved', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('public_profile_enabled', models.BooleanField(default=False)),
                ('public_profile_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('cohort_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('cohort_name', models.CharField(blank=True, max_length=255)),
                ('mentor_name', models.CharField(blank=True, max_length=255)),
                ('next_cohort_event', models.JSONField(blank=True, default=dict, help_text='{title, date, type: "mentorship|submission"}')),
                ('cohort_completion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('leaderboard_rank_global', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('leaderboard_rank_cohort', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('notifications_unread', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('notifications_urgent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('curriculum_progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('next_module_title', models.CharField(blank=True, max_length=255)),
                ('ai_coach_nudge', models.TextField(blank=True)),
                ('ai_action_plan', models.JSONField(blank=True, default=list, help_text='Array of prioritized actions')),
                ('days_to_renewal', models.IntegerField(blank=True, null=True)),
                ('can_upgrade_to_premium', models.BooleanField(default=False)),
                ('needs_mentor_feedback', models.BooleanField(default=False)),
                ('payment_overdue', models.BooleanField(default=False)),
                ('profile_incomplete', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_active_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_dashboard_cache',
                'indexes': [models.Index(fields=['user', 'updated_at'], name='student_das_user_id_107133_idx'), models.Index(fields=['cohort_id'], name='student_das_cohort__1f19d6_idx'), models.Index(fields=['leaderboard_rank_global'], name='student_das_leaderb_40a7b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardUpdateQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], db_index=True, default='normal', max_length=10)),
                ('reason', models.CharField(help_text='Event that triggered update: "mission_completed", "habit_logged", etc', max_length=100)),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_update_queue',
                'ordering': ['-priority', 'queued_at'],
                'indexes': [models.Index(fields=['user', 'priority'], name='dashboard_u_user_id_509c47_idx'), models.Index(fields=['priority', 'queued_at'], name='dashboard_u_priorit_2403cf_idx'), models.Index(fields=['processed_at'], name='dashboard_u_process_376fc3_idx')],
            },
        ),
    ]
