# Generated by Django 5.2.9 on 2025-12-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('program_director', 'Program Director'), ('mentor', 'Mentor'), ('mentee', 'Mentee'), ('student', 'Student'), ('finance', 'Finance'), ('finance_admin', 'Finance Admin'), ('sponsor_admin', 'Sponsor/Employer Admin'), ('analyst', 'Analyst')], max_length=50, unique=True),
        ),
    ]
