# Generated by Django 4.2.26 on 2025-11-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career_goals',
            field=models.TextField(blank=True, help_text='Career goals and aspirations for TalentScope baseline', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cyber_exposure_level',
            field=models.CharField(blank=True, choices=[('none', 'No Experience'), ('beginner', 'Beginner (Some Awareness)'), ('intermediate', 'Intermediate (Some Training)'), ('advanced', 'Advanced (Professional Experience)')], help_text='Current cyber security exposure level for TalentScope baseline', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_learning_style',
            field=models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('kinesthetic', 'Kinesthetic'), ('reading', 'Reading/Writing'), ('mixed', 'Mixed')], help_text='Preferred learning style for TalentScope calculations', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('program_director', 'Program Director'), ('mentor', 'Mentor'), ('mentee', 'Mentee'), ('student', 'Student'), ('finance', 'Finance'), ('sponsor_admin', 'Sponsor/Employer Admin'), ('analyst', 'Analyst')], max_length=50, unique=True),
        ),
    ]
