# Generated by Django 5.2.9 on 2026-01-07 18:48
# Updated to handle case where column may not exist or already renamed

from django.db import migrations, models


def rename_email_verification_token_created_column(apps, schema_editor):
    """Rename email_verification_token_created to email_token_created_at if it exists."""
    db_table = 'users'
    
    with schema_editor.connection.cursor() as cursor:
        # Check if old column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = %s AND column_name = 'email_verification_token_created'
        """, [db_table])
        
        old_column_exists = cursor.fetchone() is not None
        
        # Check if new column already exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = %s AND column_name = 'email_token_created_at'
        """, [db_table])
        
        new_column_exists = cursor.fetchone() is not None
        
        if old_column_exists and not new_column_exists:
            # Rename the column
            cursor.execute("""
                ALTER TABLE users 
                RENAME COLUMN email_verification_token_created TO email_token_created_at
            """)
            print("✅ Renamed 'email_verification_token_created' to 'email_token_created_at'")
        elif new_column_exists:
            print("✅ Column 'email_token_created_at' already exists")
        else:
            # Neither exists, create the new one
            cursor.execute("""
                ALTER TABLE users 
                ADD COLUMN email_token_created_at TIMESTAMP WITH TIME ZONE NULL
            """)
            print("✅ Created 'email_token_created_at' column")


def reverse_rename(apps, schema_editor):
    """Reverse the rename operation."""
    db_table = 'users'
    
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = %s AND column_name = 'email_token_created_at'
        """, [db_table])
        
        if cursor.fetchone():
            cursor.execute("""
                ALTER TABLE users 
                RENAME COLUMN email_token_created_at TO email_verification_token_created
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # Update Django's migration state AND handle database rename safely
        migrations.SeparateDatabaseAndState(
            # Database operation: safely rename column if it exists
            database_operations=[
                migrations.RunPython(
                    rename_email_verification_token_created_column,
                    reverse_code=reverse_rename
                ),
            ],
            # State operation: update Django's model state
            state_operations=[
                migrations.RenameField(
                    model_name='user',
                    old_name='email_verification_token_created',
                    new_name='email_token_created_at',
                ),
            ],
        ),
    ]
