# Generated by Django 5.2.8 on 2025-11-30 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_career_goals_user_cyber_exposure_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='rate_limit',
        ),
        migrations.AddField(
            model_name='apikey',
            name='owner_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='owner_type',
            field=models.CharField(choices=[('user', 'User'), ('org', 'Organization'), ('service', 'Service Account')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='apikey',
            name='rate_limit_per_min',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
