# Generated by Django 5.2.9 on 2025-12-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profiling_complete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profiling_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profiling_session_id',
            field=models.UUIDField(blank=True, help_text='Completed profiling session ID', null=True),
        ),
    ]
