# Generated by Django 5.2.9 on 2025-12-04 19:49

from django.db import migrations, models


def add_missing_columns(apps, schema_editor):
    """Add columns only if they don't exist"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check and add each column if it doesn't exist
        columns_to_add = [
            ('profile_complete', 'BOOLEAN DEFAULT FALSE'),
            ('onboarding_complete', 'BOOLEAN DEFAULT FALSE'),
            ('is_mentor', 'BOOLEAN DEFAULT FALSE'),
            ('mentor_capacity_weekly', 'INTEGER DEFAULT 10'),
            ('mentor_availability', 'JSONB DEFAULT \'{}\'::jsonb'),
            ('mentor_specialties', 'JSONB DEFAULT \'[]\'::jsonb'),
            ('cyber_exposure_level', 'VARCHAR(20)'),
        ]
        
        for col_name, col_def in columns_to_add:
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='users' AND column_name=%s
            """, [col_name])
            if not cursor.fetchone():
                cursor.execute(f'ALTER TABLE users ADD COLUMN {col_name} {col_def}')


def reverse_migration(apps, schema_editor):
    """Remove columns if they exist"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        columns_to_remove = [
            'profile_complete', 'onboarding_complete', 'is_mentor',
            'mentor_capacity_weekly', 'mentor_availability',
            'mentor_specialties', 'cyber_exposure_level'
        ]
        for col_name in columns_to_remove:
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='users' AND column_name=%s
            """, [col_name])
            if cursor.fetchone():
                cursor.execute(f'ALTER TABLE users DROP COLUMN IF EXISTS {col_name}')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20251204_1936'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_missing_columns, reverse_migration),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='profile_complete',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='user',
                    name='onboarding_complete',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='user',
                    name='is_mentor',
                    field=models.BooleanField(db_index=True, default=False),
                ),
                migrations.AddField(
                    model_name='user',
                    name='mentor_capacity_weekly',
                    field=models.IntegerField(default=10),
                ),
                migrations.AddField(
                    model_name='user',
                    name='mentor_availability',
                    field=models.JSONField(blank=True, default=dict),
                ),
                migrations.AddField(
                    model_name='user',
                    name='mentor_specialties',
                    field=models.JSONField(blank=True, default=list),
                ),
                migrations.AddField(
                    model_name='user',
                    name='cyber_exposure_level',
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ('none', 'No Experience'),
                            ('beginner', 'Beginner (Some Awareness)'),
                            ('intermediate', 'Intermediate (Some Training)'),
                            ('advanced', 'Advanced (Professional Experience)')
                        ],
                        help_text='Current cyber security exposure level for TalentScope baseline',
                        max_length=20,
                        null=True
                    ),
                ),
            ],
        ),
    ]
