# Generated by Django 5.2.8 on 2025-12-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_profile_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mentor_availability',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='mentor_capacity_weekly',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='mentor_specialties',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
