# Generated by Django 5.2.8 on 2025-11-30 14:02

import uuid
from django.db import migrations, models


def generate_uuids_for_apikeys(apps, schema_editor):
    """Generate UUIDs for existing APIKey records."""
    APIKey = apps.get_model('users', 'APIKey')
    for apikey in APIKey.objects.all():
        apikey.new_id = uuid.uuid4()
        apikey.save(update_fields=['new_id'])


def reverse_generate_uuids(apps, schema_editor):
    """Reverse operation - not needed but required for migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_mentor_user_mentor_availability_and_more'),
    ]

    operations = [
        # Step 1: Add new UUID field
        migrations.AddField(
            model_name='apikey',
            name='new_id',
            field=models.UUIDField(null=True, editable=False),
        ),
        # Step 2: Generate UUIDs for existing records
        migrations.RunPython(generate_uuids_for_apikeys, reverse_generate_uuids),
        # Step 3: Remove old id field (this will drop the primary key constraint)
        migrations.RemoveField(
            model_name='apikey',
            name='id',
        ),
        # Step 4: Rename new_id to id and make it primary key
        migrations.RenameField(
            model_name='apikey',
            old_name='new_id',
            new_name='id',
        ),
        # Step 5: Set as primary key
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
