# Generated by Django 5.2.9 on 2025-12-13 14:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('current_self_complete', 'Current Self Complete'), ('future_you_complete', 'Future You Complete'), ('finished', 'Finished')], db_index=True, default='started', max_length=30)),
                ('current_self_assessment', models.JSONField(blank=True, default=dict, help_text='{skills: {...}, behaviors: {...}, learning_style: {...}}')),
                ('futureyou_persona', models.JSONField(blank=True, default=dict, help_text='{name: "Cyber Sentinel", archetype: "Defender", skills: [...]}')),
                ('recommended_track_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('track_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score 0.0-1.0', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiler_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profilersessions',
            },
        ),
        migrations.CreateModel(
            name='ProfilerAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_key', models.CharField(db_index=True, help_text='e.g., "skills.networking", "behaviors.discipline"', max_length=255)),
                ('answer', models.JSONField(help_text='{value: 7, comment: "Experienced with Wireshark"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='profiler.profilersession')),
            ],
            options={
                'db_table': 'profileranswers',
            },
        ),
        migrations.AddIndex(
            model_name='profilersession',
            index=models.Index(fields=['user', 'status'], name='profilerses_user_id_df08ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='profilersession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'started')), fields=('user', 'status'), name='unique_active_session'),
        ),
        migrations.AddIndex(
            model_name='profileranswer',
            index=models.Index(fields=['session', 'question_key'], name='profilerans_session_94fc27_idx'),
        ),
    ]
