# Generated by Django 5.2.9 on 2025-12-04 19:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilerAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_key', models.CharField(db_index=True, help_text='e.g., "skills.networking", "behaviors.discipline"', max_length=255)),
                ('answer', models.JSONField(help_text='{value: 7, comment: "Experienced with Wireshark"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profileranswers',
            },
        ),
        migrations.CreateModel(
            name='ProfilerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('current_self_complete', 'Current Self Complete'), ('future_you_complete', 'Future You Complete'), ('finished', 'Finished')], db_index=True, default='started', max_length=30)),
                ('current_self_assessment', models.JSONField(blank=True, default=dict, help_text='{skills: {...}, behaviors: {...}, learning_style: {...}}')),
                ('futureyou_persona', models.JSONField(blank=True, default=dict, help_text='{name: "Cyber Sentinel", archetype: "Defender", skills: [...]}')),
                ('recommended_track_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('track_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score 0.0-1.0', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profilersessions',
            },
        ),
    ]
