# Generated by Django 4.2.26 on 2025-12-04 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiler_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileranswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='profiler.profilersession'),
        ),
        migrations.AddIndex(
            model_name='profilersession',
            index=models.Index(fields=['user', 'status'], name='profilerses_user_id_df08ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='profilersession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'started')), fields=('user', 'status'), name='unique_active_session'),
        ),
        migrations.AddIndex(
            model_name='profileranswer',
            index=models.Index(fields=['session', 'question_key'], name='profilerans_session_94fc27_idx'),
        ),
    ]
