# Generated by Django 5.2.9 on 2025-12-24 10:38

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilerQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('aptitude', 'Aptitude'), ('behavioral', 'Behavioral')], db_index=True, max_length=20)),
                ('answer_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('scale', 'Scale (1-10)'), ('likert', 'Likert Scale'), ('text', 'Text Response'), ('boolean', 'Yes/No')], max_length=20)),
                ('question_text', models.TextField()),
                ('question_order', models.IntegerField(db_index=True, default=0)),
                ('options', models.JSONField(blank=True, default=list, help_text='For multiple choice: ["Option 1", "Option 2", ...]')),
                ('correct_answer', models.JSONField(blank=True, help_text='Correct answer for aptitude questions', null=True)),
                ('points', models.IntegerField(default=1, help_text='Points awarded for correct answer')),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags: ["networking", "problem-solving"]')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profilerquestions',
                'ordering': ['question_type', 'question_order'],
            },
        ),
        migrations.CreateModel(
            name='ProfilerResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.DecimalField(decimal_places=2, help_text='Overall profiling score 0-100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('aptitude_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('behavioral_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('aptitude_breakdown', models.JSONField(default=dict, help_text='Category scores: {networking: 85, security: 72, ...}')),
                ('behavioral_traits', models.JSONField(default=dict, help_text='Behavioral analysis: {leadership: 8, teamwork: 9, ...}')),
                ('strengths', models.JSONField(default=list, help_text='Identified strengths')),
                ('areas_for_growth', models.JSONField(default=list, help_text='Areas for improvement')),
                ('recommended_tracks', models.JSONField(default=list, help_text='Recommended tracks: [{track_id: "...", confidence: 0.85, reason: "..."}]')),
                ('learning_path_suggestions', models.JSONField(default=list, help_text='Suggested learning paths')),
                ('och_mapping', models.JSONField(default=dict, help_text='Mapping to OCH system: {tier: 1, foundations: [...], tracks: [...]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profilerresults',
            },
        ),
        migrations.RemoveConstraint(
            model_name='profilersession',
            name='unique_active_session',
        ),
        migrations.RenameField(
            model_name='profilersession',
            old_name='created_at',
            new_name='started_at',
        ),
        migrations.AddField(
            model_name='profileranswer',
            name='is_correct',
            field=models.BooleanField(blank=True, help_text='For aptitude questions', null=True),
        ),
        migrations.AddField(
            model_name='profileranswer',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileranswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='admin_reset_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reset this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiler_resets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='aptitude_responses',
            field=models.JSONField(blank=True, default=dict, help_text='Aptitude test responses: {question_id: answer, ...}'),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='aptitude_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall aptitude score 0-100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='behavioral_profile',
            field=models.JSONField(blank=True, default=dict, help_text='Behavioral analysis: {traits: {...}, strengths: [...], areas_for_growth: [...]}'),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='behavioral_responses',
            field=models.JSONField(blank=True, default=dict, help_text='Behavioral test responses: {question_id: answer, ...}'),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='current_section',
            field=models.CharField(default='welcome', help_text='Current section: welcome, instructions, aptitude, behavioral, results', max_length=50),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='session_token',
            field=models.CharField(blank=True, db_index=True, help_text='Unique session token for Redis tracking', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='strengths',
            field=models.JSONField(blank=True, default=list, help_text='Identified strengths: ["analytical thinking", "problem solving", ...]'),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='time_spent_seconds',
            field=models.IntegerField(default=0, help_text='Total time spent in seconds'),
        ),
        migrations.AddField(
            model_name='profilersession',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profileranswer',
            name='answer',
            field=models.JSONField(help_text='Answer data: {value: 7, text: "Experienced with Wireshark"}'),
        ),
        migrations.AlterField(
            model_name='profilersession',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('aptitude_complete', 'Aptitude Complete'), ('behavioral_complete', 'Behavioral Complete'), ('current_self_complete', 'Current Self Complete'), ('future_you_complete', 'Future You Complete'), ('finished', 'Finished'), ('locked', 'Locked')], db_index=True, default='started', max_length=30),
        ),
        migrations.AddIndex(
            model_name='profilersession',
            index=models.Index(fields=['user', 'is_locked'], name='profilerses_user_id_6da7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='profilersession',
            index=models.Index(fields=['session_token'], name='profilerses_session_c6bc54_idx'),
        ),
        migrations.AddIndex(
            model_name='profilerquestion',
            index=models.Index(fields=['question_type', 'is_active'], name='profilerque_questio_0e4ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='profilerquestion',
            index=models.Index(fields=['category'], name='profilerque_categor_2e0cfa_idx'),
        ),
        migrations.AddField(
            model_name='profileranswer',
            name='question',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='profiler.profilerquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='profileranswer',
            unique_together={('session', 'question')},
        ),
        migrations.AddIndex(
            model_name='profileranswer',
            index=models.Index(fields=['session', 'question'], name='profilerans_session_9ab3bc_idx'),
        ),
        migrations.AddField(
            model_name='profilerresult',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='profiler.profilersession'),
        ),
        migrations.AddField(
            model_name='profilerresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiler_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='profilerresult',
            index=models.Index(fields=['user'], name='profilerres_user_id_06d847_idx'),
        ),
        migrations.AddIndex(
            model_name='profilerresult',
            index=models.Index(fields=['session'], name='profilerres_session_e6287c_idx'),
        ),
    ]
