# Generated by Django 5.2.9 on 2025-12-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0002_profilerquestion_profilerresult_and_more'),
    ]

    operations = [
        # First, ensure all existing records have a question (if any exist)
        migrations.RunPython(
            migrations.RunPython.noop,  # No-op since ProfilerQuestion is new
            migrations.RunPython.noop
        ),
        # Then make the field required
        migrations.AlterField(
            model_name='profileranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='profiler.profilerquestion'),
        ),
    ]






