# Generated by Django 5.2.9 on 2025-12-24 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0003_make_profileranswer_question_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileranswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='profiler.profilerquestion'),
        ),
    ]
