# Generated by Django 5.2.9 on 2025-12-13 14:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('behavior_type', models.CharField(choices=[('study_consistency', 'Study Consistency'), ('mission_completion', 'Mission Completion'), ('reflection_frequency', 'Reflection Frequency'), ('engagement_level', 'Engagement Level'), ('help_seeking', 'Help Seeking'), ('collaboration', 'Collaboration')], db_index=True, max_length=50)),
                ('value', models.DecimalField(decimal_places=2, help_text='Behavioral metric value', max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (e.g., time_of_day, duration)')),
                ('source', models.CharField(choices=[('habit_log', 'Habit Log'), ('mission', 'Mission'), ('reflection', 'Reflection'), ('session', 'Mentor Session'), ('system', 'System Event')], default='system', max_length=50)),
                ('source_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ts_behavior_signals',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['mentee', 'behavior_type'], name='ts_behavior_mentee__a6a256_idx'), models.Index(fields=['mentee', 'recorded_at'], name='ts_behavior_mentee__95b3b1_idx'), models.Index(fields=['behavior_type', 'recorded_at'], name='ts_behavior_behavio_64f87d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MentorInfluence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('submission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Submission rate percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('code_quality_score', models.DecimalField(blank=True, decimal_places=2, help_text='Code quality score 0-100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mission_completion_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Mission completion rate percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('performance_score', models.DecimalField(blank=True, decimal_places=2, help_text='Overall performance score', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('influence_index', models.DecimalField(blank=True, decimal_places=1, help_text='Mentor influence index 0-10', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_influences', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influence_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ts_mentor_influence',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['mentee', 'period_start'], name='ts_mentor_i_mentee__5f6d93_idx'), models.Index(fields=['mentor', 'period_start'], name='ts_mentor_i_mentor__8b6201_idx'), models.Index(fields=['mentee', 'mentor'], name='ts_mentor_i_mentee__012070_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadinessSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('core_readiness_score', models.DecimalField(decimal_places=2, help_text='Core readiness score 0-100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_readiness_window', models.CharField(blank=True, help_text='e.g., "3-6 months"', max_length=50, null=True)),
                ('learning_velocity', models.DecimalField(blank=True, decimal_places=2, help_text='Learning velocity (points per month)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('career_readiness_stage', models.CharField(choices=[('exploring', 'Exploring'), ('building', 'Building'), ('emerging', 'Emerging'), ('ready', 'Ready')], db_index=True, default='exploring', max_length=20)),
                ('job_fit_score', models.DecimalField(blank=True, decimal_places=2, help_text='Job fit score 0-100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hiring_timeline_prediction', models.CharField(blank=True, help_text='e.g., "4-6 months"', max_length=50, null=True)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Breakdown by category (technical, practical, theoretical)')),
                ('strengths', models.JSONField(blank=True, default=list, help_text='List of identified strengths')),
                ('weaknesses', models.JSONField(blank=True, default=list, help_text='List of identified weaknesses with priorities')),
                ('missing_skills', models.JSONField(blank=True, default=list, help_text='List of missing skills with priorities')),
                ('improvement_plan', models.JSONField(blank=True, default=list, help_text='Improvement plan items')),
                ('track_benchmarks', models.JSONField(blank=True, default=dict, help_text='Track-specific benchmark data')),
                ('snapshot_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ts_readiness_snapshots',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['mentee', 'snapshot_date'], name='ts_readines_mentee__6d1e0e_idx'), models.Index(fields=['mentee', 'career_readiness_stage'], name='ts_readines_mentee__199a37_idx'), models.Index(fields=['snapshot_date'], name='ts_readines_snapsho_334d3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(db_index=True, max_length=255)),
                ('skill_category', models.CharField(db_index=True, max_length=100)),
                ('mastery_level', models.DecimalField(decimal_places=2, help_text='Mastery level 0-100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hours_practiced', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('mission', 'Mission'), ('course', 'Course'), ('portfolio', 'Portfolio'), ('assessment', 'Assessment'), ('mentor_feedback', 'Mentor Feedback')], default='mission', max_length=50)),
                ('source_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ts_skill_signals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mentee', 'skill_category'], name='ts_skill_si_mentee__dc7f74_idx'), models.Index(fields=['mentee', 'created_at'], name='ts_skill_si_mentee__8b3934_idx'), models.Index(fields=['skill_name', 'skill_category'], name='ts_skill_si_skill_n_11e337_idx')],
            },
        ),
    ]
