# Generated by Django 5.2.8 on 2025-12-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentscope', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='behaviorsignal',
            new_name='ts_behavior_mentee__a6a256_idx',
            old_name='ts_behavio_mentee__behavior_idx',
        ),
        migrations.RenameIndex(
            model_name='behaviorsignal',
            new_name='ts_behavior_mentee__95b3b1_idx',
            old_name='ts_behavio_mentee__recorded_idx',
        ),
        migrations.RenameIndex(
            model_name='behaviorsignal',
            new_name='ts_behavior_behavio_64f87d_idx',
            old_name='ts_behavio_behavior_recorded_idx',
        ),
        migrations.RenameIndex(
            model_name='mentorinfluence',
            new_name='ts_mentor_i_mentee__5f6d93_idx',
            old_name='ts_mentor__mentee__period_idx',
        ),
        migrations.RenameIndex(
            model_name='mentorinfluence',
            new_name='ts_mentor_i_mentor__8b6201_idx',
            old_name='ts_mentor__mentor__period_idx',
        ),
        migrations.RenameIndex(
            model_name='mentorinfluence',
            new_name='ts_mentor_i_mentee__012070_idx',
            old_name='ts_mentor__mentee__mentor_idx',
        ),
        migrations.RenameIndex(
            model_name='readinesssnapshot',
            new_name='ts_readines_mentee__6d1e0e_idx',
            old_name='ts_readine_mentee__snapshot_idx',
        ),
        migrations.RenameIndex(
            model_name='readinesssnapshot',
            new_name='ts_readines_mentee__199a37_idx',
            old_name='ts_readine_mentee__career_idx',
        ),
        migrations.RenameIndex(
            model_name='readinesssnapshot',
            new_name='ts_readines_snapsho_334d3e_idx',
            old_name='ts_readine_snapshot_idx',
        ),
        migrations.RenameIndex(
            model_name='skillsignal',
            new_name='ts_skill_si_mentee__dc7f74_idx',
            old_name='ts_skill_s_mentee__idx',
        ),
        migrations.RenameIndex(
            model_name='skillsignal',
            new_name='ts_skill_si_mentee__8b3934_idx',
            old_name='ts_skill_s_mentee__created_idx',
        ),
        migrations.RenameIndex(
            model_name='skillsignal',
            new_name='ts_skill_si_skill_n_11e337_idx',
            old_name='ts_skill_s_skill_n_idx',
        ),
        migrations.AlterField(
            model_name='readinesssnapshot',
            name='estimated_readiness_window',
            field=models.CharField(blank=True, help_text='e.g., "3-6 months"', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='readinesssnapshot',
            name='hiring_timeline_prediction',
            field=models.CharField(blank=True, help_text='e.g., "4-6 months"', max_length=50, null=True),
        ),
    ]
