# Generated by Django 5.2.9 on 2025-12-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talentscope', '0002_initial'),
        ('talentscope', '0002_rename_ts_behavio_mentee__behavior_idx_ts_behavior_mentee__a6a256_idx_and_more'),
    ]

    operations = [
    ]
