# Generated by Django 5.2.9 on 2025-12-23 12:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('channel_type', models.CharField(choices=[('track', 'Track Channel'), ('project', 'Project Channel'), ('interest', 'Interest Group'), ('study_group', 'Study Group'), ('official', 'Official Announcements')], default='interest', max_length=20)),
                ('icon', models.CharField(default='#', max_length=10)),
                ('color', models.CharField(default='#4F46E5', max_length=7)),
                ('member_limit', models.IntegerField(default=50)),
                ('is_private', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('track_key', models.CharField(blank=True, max_length=100, null=True)),
                ('circle_level', models.IntegerField(blank=True, null=True)),
                ('member_count', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('active_today', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='community.university')),
            ],
            options={
                'db_table': 'community_channels',
                'ordering': ['-member_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_type', models.CharField(choices=[('thread', 'Thread Summary'), ('daily_digest', 'Daily Digest'), ('weekly_recap', 'Weekly Recap')], default='thread', max_length=20)),
                ('summary', models.TextField()),
                ('key_takeaways', models.JSONField(default=list)),
                ('source_comment_count', models.IntegerField(default=0)),
                ('model_used', models.CharField(default='gpt-4', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='community.post')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_summaries', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='community.channel')),
            ],
            options={
                'db_table': 'community_ai_summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='member', max_length=20)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_channel_memberships',
            },
        ),
        migrations.CreateModel(
            name='CollabRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('room_type', models.CharField(choices=[('ctf', 'CTF Challenge'), ('hackathon', 'Hackathon'), ('project', 'Project Collaboration'), ('debate', 'Debate/Discussion')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('mission_id', models.UUIDField(blank=True, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('max_participants_per_uni', models.IntegerField(default=50)),
                ('is_public', models.BooleanField(default=True)),
                ('participant_count', models.IntegerField(default=0)),
                ('results', models.JSONField(default=dict, help_text='{"winner_university_id": "...", "scores": {...}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collab_rooms', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_rooms', to='community.communityevent')),
                ('universities', models.ManyToManyField(related_name='collab_rooms', to='community.university')),
            ],
            options={
                'db_table': 'community_collab_rooms',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='CollabRoomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_team_lead', models.BooleanField(default=False)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('individual_score', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='community.collabroom')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_participants', to='community.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_collab_participants',
            },
        ),
        migrations.CreateModel(
            name='CommunityContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contribution_type', models.CharField(choices=[('accepted_answer', 'Accepted Answer'), ('helpful_comment', 'Helpful Comment'), ('squad_leader', 'Squad Leadership'), ('challenge_win', 'Challenge Win'), ('event_host', 'Event Host'), ('mentor_session', 'Mentor Session'), ('content_creation', 'Content Creation'), ('bug_report', 'Bug Report')], max_length=30)),
                ('points_awarded', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict, help_text='{"post_id": "...", "squad_id": "...", "event_id": "..."}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_contributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReputation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_points', models.IntegerField(default=0)),
                ('weekly_points', models.IntegerField(default=0)),
                ('monthly_points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('badges', models.JSONField(default=list)),
                ('titles', models.JSONField(default=list, help_text='Special titles: ["community_mentor", "top_contributor", "ama_host"]')),
                ('posts_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('reactions_given', models.IntegerField(default=0)),
                ('reactions_received', models.IntegerField(default=0)),
                ('helpful_answers', models.IntegerField(default=0)),
                ('squads_led', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level_up_at', models.DateTimeField(blank=True, null=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_records', to='community.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_reputation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_reputation',
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseCohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('enterprise_id', models.UUIDField(blank=True, null=True)),
                ('enterprise_name', models.CharField(blank=True, max_length=200, null=True)),
                ('members', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=True)),
                ('allow_external_view', models.BooleanField(default=False)),
                ('member_count', models.IntegerField(default=0)),
                ('admin_users', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_cohorts', to='community.university')),
            ],
            options={
                'db_table': 'community_enterprise_cohorts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudySquad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('goal', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='👥', max_length=10)),
                ('color', models.CharField(default='#8B5CF6', max_length=7)),
                ('circle_level', models.IntegerField(blank=True, null=True)),
                ('track_key', models.CharField(blank=True, max_length=100, null=True)),
                ('min_members', models.IntegerField(default=4)),
                ('max_members', models.IntegerField(default=8)),
                ('is_open', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_mission', models.UUIDField(blank=True, null=True)),
                ('missions_completed', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('weekly_streak', models.IntegerField(default=0)),
                ('member_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='community.channel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_squads', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='community.university')),
            ],
            options={
                'db_table': 'community_study_squads',
                'ordering': ['-total_points', '-member_count'],
            },
        ),
        migrations.CreateModel(
            name='SquadMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('leader', 'Leader'), ('co_leader', 'Co-Leader')], default='member', max_length=20)),
                ('missions_contributed', models.IntegerField(default=0)),
                ('points_contributed', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_memberships', to=settings.AUTH_USER_MODEL)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.studysquad')),
            ],
            options={
                'db_table': 'community_squad_memberships',
            },
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['university', 'channel_type'], name='community_c_univers_17229d_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['university', 'is_private', 'is_archived'], name='community_c_univers_f9be29_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['track_key'], name='community_c_track_k_d02f52_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['circle_level'], name='community_c_circle__09c84f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('university', 'slug')},
        ),
        migrations.AddIndex(
            model_name='aisummary',
            index=models.Index(fields=['post', '-created_at'], name='community_a_post_id_f15cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='aisummary',
            index=models.Index(fields=['channel', 'summary_type'], name='community_a_channel_72917a_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['user', 'channel'], name='community_c_user_id_163bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['channel', 'role'], name='community_c_channel_bd8a53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmembership',
            unique_together={('channel', 'user')},
        ),
        migrations.AddIndex(
            model_name='collabroom',
            index=models.Index(fields=['status', 'starts_at'], name='community_c_status_c16b44_idx'),
        ),
        migrations.AddIndex(
            model_name='collabroom',
            index=models.Index(fields=['room_type', 'status'], name='community_c_room_ty_4d2029_idx'),
        ),
        migrations.AddIndex(
            model_name='collabroomparticipant',
            index=models.Index(fields=['room', 'university'], name='community_c_room_id_fc4f75_idx'),
        ),
        migrations.AddIndex(
            model_name='collabroomparticipant',
            index=models.Index(fields=['user', 'room'], name='community_c_user_id_4672d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collabroomparticipant',
            unique_together={('room', 'user')},
        ),
        migrations.AddIndex(
            model_name='communitycontribution',
            index=models.Index(fields=['user', 'contribution_type'], name='community_c_user_id_c9f683_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycontribution',
            index=models.Index(fields=['user', '-created_at'], name='community_c_user_id_f80458_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycontribution',
            index=models.Index(fields=['contribution_type', '-created_at'], name='community_c_contrib_0ef5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='communityreputation',
            index=models.Index(fields=['level', '-total_points'], name='community_r_level_83c963_idx'),
        ),
        migrations.AddIndex(
            model_name='communityreputation',
            index=models.Index(fields=['university', '-total_points'], name='community_r_univers_8f4ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='communityreputation',
            index=models.Index(fields=['-weekly_points'], name='community_r_weekly__98d3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisecohort',
            index=models.Index(fields=['enterprise_id', 'is_active'], name='community_e_enterpr_618bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisecohort',
            index=models.Index(fields=['university', 'is_active'], name='community_e_univers_71f09f_idx'),
        ),
        migrations.AddIndex(
            model_name='studysquad',
            index=models.Index(fields=['university', 'is_active'], name='community_s_univers_0ba5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='studysquad',
            index=models.Index(fields=['circle_level', 'track_key'], name='community_s_circle__5868c5_idx'),
        ),
        migrations.AddIndex(
            model_name='studysquad',
            index=models.Index(fields=['is_open', 'member_count'], name='community_s_is_open_69b434_idx'),
        ),
        migrations.AddIndex(
            model_name='squadmembership',
            index=models.Index(fields=['user', 'squad'], name='community_s_user_id_52b504_idx'),
        ),
        migrations.AddIndex(
            model_name='squadmembership',
            index=models.Index(fields=['squad', 'role'], name='community_s_squad_i_82fe96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='squadmembership',
            unique_together={('squad', 'user')},
        ),
    ]
