# Generated by Django 5.2.9 on 2025-12-17 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_create_missing_tables_if_faked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculummodule',
            options={'ordering': ['track_key', 'order_index']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module', 'order_index']},
        ),
        migrations.RenameIndex(
            model_name='curriculummodule',
            new_name='curriculumm_track_k_f394bd_idx',
            old_name='curriculumm_track_k_123abc_idx',
        ),
        migrations.RenameIndex(
            model_name='curriculummodule',
            new_name='curriculumm_track_k_10406d_idx',
            old_name='curriculumm_track_k_456def_idx',
        ),
        # Idempotent PK addition: some DBs already have `id` on these tables (e.g. when tables
        # were created outside migrations or via `schema_editor.create_model()`).
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                      -- Add `id` column if missing.
                      IF NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'user_lesson_progress'
                          AND column_name = 'id'
                      ) THEN
                        EXECUTE 'ALTER TABLE user_lesson_progress ADD COLUMN id bigint';
                      END IF;

                      -- Make `id` an identity column if it isn't one and has no default.
                      IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'user_lesson_progress'
                          AND column_name = 'id'
                          AND identity_generation IS NULL
                      )
                      AND NOT EXISTS (
                        SELECT 1
                        FROM pg_attrdef d
                        JOIN pg_attribute a ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                        WHERE d.adrelid = 'user_lesson_progress'::regclass
                          AND a.attname = 'id'
                      ) THEN
                        BEGIN
                          EXECUTE 'ALTER TABLE user_lesson_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
                        EXCEPTION WHEN others THEN
                          -- If the backend doesn't support identity alterations, ignore.
                        END;
                      END IF;

                      -- Populate NULL ids (safe even if table is empty).
                      IF EXISTS (SELECT 1 FROM user_lesson_progress WHERE id IS NULL) THEN
                        EXECUTE 'UPDATE user_lesson_progress SET id = DEFAULT WHERE id IS NULL';
                      END IF;

                      -- Enforce NOT NULL where possible.
                      BEGIN
                        EXECUTE 'ALTER TABLE user_lesson_progress ALTER COLUMN id SET NOT NULL';
                      EXCEPTION WHEN others THEN
                      END;

                      -- Add a primary key on `id` if the table has no PK.
                      IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conrelid = 'user_lesson_progress'::regclass
                          AND contype = 'p'
                      ) THEN
                        BEGIN
                          EXECUTE 'ALTER TABLE user_lesson_progress ADD PRIMARY KEY (id)';
                        EXCEPTION WHEN others THEN
                        END;
                      END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
        migrations.AddField(
            model_name='userlessonprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                      -- Add `id` column if missing.
                      IF NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'user_module_progress'
                          AND column_name = 'id'
                      ) THEN
                        EXECUTE 'ALTER TABLE user_module_progress ADD COLUMN id bigint';
                      END IF;

                      -- Make `id` an identity column if it isn't one and has no default.
                      IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'user_module_progress'
                          AND column_name = 'id'
                          AND identity_generation IS NULL
                      )
                      AND NOT EXISTS (
                        SELECT 1
                        FROM pg_attrdef d
                        JOIN pg_attribute a ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                        WHERE d.adrelid = 'user_module_progress'::regclass
                          AND a.attname = 'id'
                      ) THEN
                        BEGIN
                          EXECUTE 'ALTER TABLE user_module_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
                        EXCEPTION WHEN others THEN
                        END;
                      END IF;

                      -- Populate NULL ids (safe even if table is empty).
                      IF EXISTS (SELECT 1 FROM user_module_progress WHERE id IS NULL) THEN
                        EXECUTE 'UPDATE user_module_progress SET id = DEFAULT WHERE id IS NULL';
                      END IF;

                      -- Enforce NOT NULL where possible.
                      BEGIN
                        EXECUTE 'ALTER TABLE user_module_progress ALTER COLUMN id SET NOT NULL';
                      EXCEPTION WHEN others THEN
                      END;

                      -- Add a primary key on `id` if the table has no PK.
                      IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conrelid = 'user_module_progress'::regclass
                          AND contype = 'p'
                      ) THEN
                        BEGIN
                          EXECUTE 'ALTER TABLE user_module_progress ADD PRIMARY KEY (id)';
                        EXCEPTION WHEN others THEN
                        END;
                      END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
        migrations.AddField(
            model_name='usermoduleprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order_index'], name='lessons_module__6380c9_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'status'], name='user_lesson_user_id_64b223_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['user', 'status'], name='user_module_user_id_f0505a_idx'),
        ),
    ]
