# Generated by Django 5.2.9 on 2025-12-23 13:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_curriculummodule_options_alter_lesson_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('lesson_started', 'Lesson Started'), ('lesson_completed', 'Lesson Completed'), ('module_started', 'Module Started'), ('module_completed', 'Module Completed'), ('mission_started', 'Mission Started'), ('mission_submitted', 'Mission Submitted'), ('mission_completed', 'Mission Completed'), ('quiz_completed', 'Quiz Completed'), ('recipe_started', 'Recipe Started'), ('recipe_completed', 'Recipe Completed'), ('track_started', 'Track Started'), ('track_completed', 'Track Completed'), ('streak_milestone', 'Streak Milestone'), ('badge_earned', 'Badge Earned')], db_index=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity data: {score, time_spent, badge_name, etc.}')),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Curriculum Activity',
                'verbose_name_plural': 'Curriculum Activities',
                'db_table': 'curriculum_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., "SOCDEFENSE", "CLOUDSEC"', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('entry', 'Entry Level'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='entry', max_length=20)),
                ('program_track_id', models.UUIDField(blank=True, help_text='FK to programs.Track', null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier e.g., "shield", "cloud"', max_length=50)),
                ('color', models.CharField(blank=True, default='indigo', help_text='Theme color', max_length=20)),
                ('estimated_duration_weeks', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('module_count', models.IntegerField(default=0)),
                ('lesson_count', models.IntegerField(default=0)),
                ('mission_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curriculum Track',
                'verbose_name_plural': 'Curriculum Tracks',
                'db_table': 'curriculum_tracks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mission_id', models.UUIDField(db_index=True, help_text='FK to missions.Mission')),
                ('mission_title', models.CharField(blank=True, max_length=255)),
                ('mission_difficulty', models.CharField(blank=True, max_length=20)),
                ('mission_estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('is_required', models.BooleanField(default=True, help_text='Required to complete module')),
                ('recommended_order', models.IntegerField(default=0, help_text='Order within module missions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Module Mission',
                'verbose_name_plural': 'Module Missions',
                'db_table': 'module_missions',
                'ordering': ['module', 'recommended_order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipe_id', models.UUIDField(db_index=True, help_text='FK to recipes.Recipe')),
                ('recipe_title', models.CharField(blank=True, max_length=255)),
                ('recipe_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('recipe_difficulty', models.CharField(blank=True, max_length=20)),
                ('relevance_score', models.DecimalField(decimal_places=2, default=1.0, help_text='How relevant is this recipe to the module (0-1)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recipe Recommendation',
                'verbose_name_plural': 'Recipe Recommendations',
                'db_table': 'curriculum_recipe_recommendations',
                'ordering': ['module', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='UserMissionProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='not_started', max_length=20)),
                ('mission_submission_id', models.UUIDField(blank=True, help_text='FK to missions.MissionSubmission', null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('feedback', models.TextField(blank=True)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Mission Progress',
                'verbose_name_plural': 'User Mission Progress',
                'db_table': 'user_curriculum_mission_progress',
            },
        ),
        migrations.CreateModel(
            name='UserTrackProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('modules_completed', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('missions_completed', models.IntegerField(default=0)),
                ('total_time_spent_minutes', models.IntegerField(default=0)),
                ('estimated_completion_date', models.DateField(blank=True, null=True)),
                ('circle_level', models.IntegerField(default=1, help_text='OCH Circle level (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('phase', models.IntegerField(default=1, help_text='Phase within circle (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('total_points', models.IntegerField(default=0)),
                ('current_streak_days', models.IntegerField(default=0)),
                ('longest_streak_days', models.IntegerField(default=0)),
                ('total_badges', models.IntegerField(default=0)),
                ('university_rank', models.IntegerField(blank=True, null=True)),
                ('global_rank', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Track Progress',
                'verbose_name_plural': 'User Track Progress',
                'db_table': 'user_track_progress',
            },
        ),
        migrations.AlterModelOptions(
            name='curriculummodule',
            options={'ordering': ['track_key', 'order_index'], 'verbose_name': 'Curriculum Module', 'verbose_name_plural': 'Curriculum Modules'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module', 'order_index'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='userlessonprogress',
            options={'verbose_name': 'User Lesson Progress', 'verbose_name_plural': 'User Lesson Progress'},
        ),
        migrations.AlterModelOptions(
            name='usermoduleprogress',
            options={'verbose_name': 'User Module Progress', 'verbose_name_plural': 'User Module Progress'},
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='entitlement_tier',
            field=models.CharField(choices=[('all', 'All Tiers'), ('starter_enhanced', 'Starter Enhanced (First 6mo)'), ('starter_normal', 'Starter Normal'), ('professional', 'Professional Only')], default='all', help_text='Minimum subscription tier required', max_length=20),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Required to complete track'),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='lesson_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('capstone', 'Capstone')], default='beginner', help_text='Module difficulty level', max_length=20),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='mentor_notes',
            field=models.TextField(blank=True, help_text='Mentor guidance notes (Professional tier only)'),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='mission_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Required to complete module'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('guide', 'Guide/Article'), ('quiz', 'Quiz'), ('assessment', 'Assessment'), ('lab', 'Hands-on Lab'), ('reading', 'Reading Material')], default='video', help_text='Type of lesson content', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='For video: watch percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='quiz_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='quiz_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='time_spent_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='blocked_by_mission_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='completion_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Waiting on mission completion'),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='lessons_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='missions_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='time_spent_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usermoduleprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_type'], name='lessons_lesson__5ca97f_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['lesson', 'status'], name='user_lesson_lesson__b56751_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['module', '-completion_percentage'], name='user_module_module__7b8549_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['user', 'is_blocked'], name='user_module_user_id_55cb70_idx'),
        ),
        migrations.AddField(
            model_name='curriculumactivity',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='curriculumactivity',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='curriculum.curriculummodule'),
        ),
        migrations.AddField(
            model_name='curriculumactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='curriculumtrack',
            index=models.Index(fields=['code', 'is_active'], name='curriculum__code_4a93ec_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumtrack',
            index=models.Index(fields=['level', 'is_active'], name='curriculum__level_8c6c69_idx'),
        ),
        migrations.AddField(
            model_name='curriculumactivity',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='curriculum.curriculumtrack'),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='track',
            field=models.ForeignKey(blank=True, help_text='FK to CurriculumTrack', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='curriculum.curriculumtrack'),
        ),
        migrations.AddIndex(
            model_name='curriculummodule',
            index=models.Index(fields=['track', 'order_index'], name='curriculumm_track_i_c68cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculummodule',
            index=models.Index(fields=['level', 'entitlement_tier'], name='curriculumm_level_a6d9fa_idx'),
        ),
        migrations.AddField(
            model_name='modulemission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_missions', to='curriculum.curriculummodule'),
        ),
        migrations.AddField(
            model_name='reciperecommendation',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_recommendations', to='curriculum.curriculummodule'),
        ),
        migrations.AddField(
            model_name='usermissionprogress',
            name='module_mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='curriculum.modulemission'),
        ),
        migrations.AddField(
            model_name='usermissionprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_mission_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertrackprogress',
            name='current_module',
            field=models.ForeignKey(blank=True, help_text='Current active module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='curriculum.curriculummodule'),
        ),
        migrations.AddField(
            model_name='usertrackprogress',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='curriculum.curriculumtrack'),
        ),
        migrations.AddField(
            model_name='usertrackprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='curriculumactivity',
            index=models.Index(fields=['user', '-created_at'], name='curriculum__user_id_e46302_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumactivity',
            index=models.Index(fields=['activity_type', '-created_at'], name='curriculum__activit_4508fa_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumactivity',
            index=models.Index(fields=['track', '-created_at'], name='curriculum__track_i_ef4578_idx'),
        ),
        migrations.AddIndex(
            model_name='modulemission',
            index=models.Index(fields=['module', 'recommended_order'], name='module_miss_module__22c8ce_idx'),
        ),
        migrations.AddIndex(
            model_name='modulemission',
            index=models.Index(fields=['mission_id'], name='module_miss_mission_89472b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modulemission',
            unique_together={('module', 'mission_id')},
        ),
        migrations.AddIndex(
            model_name='reciperecommendation',
            index=models.Index(fields=['module', 'order_index'], name='curriculum__module__28a64d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reciperecommendation',
            unique_together={('module', 'recipe_id')},
        ),
        migrations.AddIndex(
            model_name='usermissionprogress',
            index=models.Index(fields=['user', 'status'], name='user_curric_user_id_a6824b_idx'),
        ),
        migrations.AddIndex(
            model_name='usermissionprogress',
            index=models.Index(fields=['module_mission', 'status'], name='user_curric_module__5fa6a0_idx'),
        ),
        migrations.AddIndex(
            model_name='usermissionprogress',
            index=models.Index(fields=['mission_submission_id'], name='user_curric_mission_8603a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermissionprogress',
            unique_together={('user', 'module_mission')},
        ),
        migrations.AddIndex(
            model_name='usertrackprogress',
            index=models.Index(fields=['user', 'track'], name='user_track__user_id_b77a10_idx'),
        ),
        migrations.AddIndex(
            model_name='usertrackprogress',
            index=models.Index(fields=['track', '-completion_percentage'], name='user_track__track_i_ce494f_idx'),
        ),
        migrations.AddIndex(
            model_name='usertrackprogress',
            index=models.Index(fields=['user', '-last_activity_at'], name='user_track__user_id_cedb01_idx'),
        ),
        migrations.AddIndex(
            model_name='usertrackprogress',
            index=models.Index(fields=['circle_level', 'phase'], name='user_track__circle__a0d99c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usertrackprogress',
            unique_together={('user', 'track')},
        ),
    ]
