# Generated by Django 5.2.9 on 2025-12-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cohortprogress',
            new_name='cohort_prog_user_id_3ea554_idx',
            old_name='cohort_prog_user_id_cohort_idx',
        ),
        migrations.RenameIndex(
            model_name='communityactivity',
            new_name='community_a_created_cb3449_idx',
            old_name='community_a_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='communityactivity',
            new_name='community_a_activit_e0e8d3_idx',
            old_name='community_a_activity_created_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardevent',
            new_name='dashboard_e_user_id_32d787_idx',
            old_name='dashboard_e_user_id_date_created_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardevent',
            new_name='dashboard_e_date_c563e1_idx',
            old_name='dashboard_e_date_urgency_idx',
        ),
        migrations.RenameIndex(
            model_name='gamificationpoints',
            new_name='gamificatio_user_id_a378ec_idx',
            old_name='gamificatio_user_id_points_idx',
        ),
        migrations.RenameIndex(
            model_name='mentorshipsession',
            new_name='mentorship__user_id_7d3b57_idx',
            old_name='mentorship__user_id_next_s_created_idx',
        ),
        migrations.RenameIndex(
            model_name='portfolioitem',
            new_name='portfolio_i_user_id_08ed52_idx',
            old_name='portfolio_i_user_id_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='readinessscore',
            new_name='readiness_s_user_id_2d7303_idx',
            old_name='readiness_s_user_id_updated_idx',
        ),
    ]
