# Generated by Django 5.2.8 on 2025-12-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # Enable RLS on sponsor_dashboard_cache
            sql="""
            ALTER TABLE sponsor_dashboard_cache ENABLE ROW LEVEL SECURITY;
            
            CREATE POLICY sponsor_cache_policy ON sponsor_dashboard_cache
            FOR ALL
            USING (
                org_id IN (
                    SELECT id FROM organizations 
                    WHERE id = sponsor_dashboard_cache.org_id
                    AND org_type = 'sponsor'
                )
            );
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS sponsor_cache_policy ON sponsor_dashboard_cache;
            ALTER TABLE sponsor_dashboard_cache DISABLE ROW LEVEL SECURITY;
            """
        ),
        migrations.RunSQL(
            # Enable RLS on sponsor_cohort_dashboard
            sql="""
            ALTER TABLE sponsor_cohort_dashboard ENABLE ROW LEVEL SECURITY;
            
            CREATE POLICY sponsor_cohort_policy ON sponsor_cohort_dashboard
            FOR ALL
            USING (
                org_id IN (
                    SELECT id FROM organizations 
                    WHERE id = sponsor_cohort_dashboard.org_id
                    AND org_type = 'sponsor'
                )
            );
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS sponsor_cohort_policy ON sponsor_cohort_dashboard;
            ALTER TABLE sponsor_cohort_dashboard DISABLE ROW LEVEL SECURITY;
            """
        ),
        migrations.RunSQL(
            # Enable RLS on sponsor_student_aggregates
            sql="""
            ALTER TABLE sponsor_student_aggregates ENABLE ROW LEVEL SECURITY;
            
            CREATE POLICY sponsor_student_policy ON sponsor_student_aggregates
            FOR ALL
            USING (
                org_id IN (
                    SELECT id FROM organizations 
                    WHERE id = sponsor_student_aggregates.org_id
                    AND org_type = 'sponsor'
                )
            );
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS sponsor_student_policy ON sponsor_student_aggregates;
            ALTER TABLE sponsor_student_aggregates DISABLE ROW LEVEL SECURITY;
            """
        ),
        migrations.RunSQL(
            # Enable RLS on sponsor_codes
            sql="""
            ALTER TABLE sponsor_codes ENABLE ROW LEVEL SECURITY;
            
            CREATE POLICY sponsor_codes_policy ON sponsor_codes
            FOR ALL
            USING (
                org_id IN (
                    SELECT id FROM organizations 
                    WHERE id = sponsor_codes.org_id
                    AND org_type = 'sponsor'
                )
            );
            """,
            reverse_sql="""
            DROP POLICY IF EXISTS sponsor_codes_policy ON sponsor_codes;
            ALTER TABLE sponsor_codes DISABLE ROW LEVEL SECURITY;
            """
        ),
    ]
