# Generated by Django 5.2.9 on 2025-12-13 14:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeMentorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_sessions', models.IntegerField(default=12)),
                ('sessions_used', models.IntegerField(default=0)),
                ('mentor_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_assignments', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menteementorassignments',
            },
        ),
        migrations.CreateModel(
            name='MentorFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('director_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentorflags',
            },
        ),
        migrations.CreateModel(
            name='MentorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('one_on_one', 'One-on-One'), ('group', 'Group'), ('capstone_review', 'Capstone Review'), ('goal_review', 'Goal Review')], max_length=20)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('zoom_url', models.URLField(blank=True)),
                ('calendar_event_id', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('outcomes', models.JSONField(blank=True, default=dict)),
                ('attended', models.BooleanField(default=False)),
                ('no_show_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentorship_coordination.menteementorassignment')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_sessions', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentorsessions',
            },
        ),
        migrations.CreateModel(
            name='MentorWorkQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('mission_review', 'Mission Review'), ('goal_feedback', 'Goal Feedback'), ('session_notes', 'Session Notes'), ('risk_flag', 'Risk Flag')], max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('sla_hours', models.IntegerField(default=48)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_work_items', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_queue_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentorworkqueue',
            },
        ),
        migrations.AddIndex(
            model_name='menteementorassignment',
            index=models.Index(fields=['status'], name='menteemento_status_5e3993_idx'),
        ),
        migrations.AddIndex(
            model_name='menteementorassignment',
            index=models.Index(fields=['mentor', 'status'], name='menteemento_mentor__a2fbce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menteementorassignment',
            unique_together={('mentee', 'mentor')},
        ),
        migrations.AddIndex(
            model_name='mentorflag',
            index=models.Index(fields=['mentee'], name='mentorflags_mentee__952626_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorflag',
            index=models.Index(fields=['mentor'], name='mentorflags_mentor__99c111_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorflag',
            index=models.Index(fields=['resolved'], name='mentorflags_resolve_7c6981_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['mentor', 'start_time'], name='mentorsessi_mentor__7ae068_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['mentee', 'start_time'], name='mentorsessi_mentee__303792_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorworkqueue',
            index=models.Index(fields=['mentor', 'status'], name='mentorworkq_mentor__b7ee6a_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorworkqueue',
            index=models.Index(fields=['due_at'], name='mentorworkq_due_at_2823e8_idx'),
        ),
    ]
