# Generated by Django 5.2.9 on 2025-12-06 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentorship_coordination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menteementorassignment',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menteementorassignment',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorflag',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorflag',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentorship_coordination.menteementorassignment'),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorworkqueue',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_work_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorworkqueue',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_queue_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='menteementorassignment',
            index=models.Index(fields=['status'], name='menteemento_status_5e3993_idx'),
        ),
        migrations.AddIndex(
            model_name='menteementorassignment',
            index=models.Index(fields=['mentor', 'status'], name='menteemento_mentor__a2fbce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menteementorassignment',
            unique_together={('mentee', 'mentor')},
        ),
        migrations.AddIndex(
            model_name='mentorflag',
            index=models.Index(fields=['mentee'], name='mentorflags_mentee__952626_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorflag',
            index=models.Index(fields=['mentor'], name='mentorflags_mentor__99c111_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorflag',
            index=models.Index(fields=['resolved'], name='mentorflags_resolve_7c6981_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['mentor', 'start_time'], name='mentorsessi_mentor__7ae068_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['mentee', 'start_time'], name='mentorsessi_mentee__303792_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorworkqueue',
            index=models.Index(fields=['mentor', 'status'], name='mentorworkq_mentor__b7ee6a_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorworkqueue',
            index=models.Index(fields=['due_at'], name='mentorworkq_due_at_2823e8_idx'),
        ),
    ]
