# Generated by Django 5.2.9 on 2025-12-17 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_coordination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Idempotent schema updates: these columns may already exist in some DBs.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                      -- NOTE: We default to empty string for URL fields to match Django's blank string behavior.
                      EXECUTE 'ALTER TABLE mentorsessions ADD COLUMN IF NOT EXISTS is_closed boolean NOT NULL DEFAULT false';
                      EXECUTE 'ALTER TABLE mentorsessions ADD COLUMN IF NOT EXISTS recording_url varchar(200) NOT NULL DEFAULT ''''';
                      EXECUTE 'ALTER TABLE mentorsessions ADD COLUMN IF NOT EXISTS transcript_url varchar(200) NOT NULL DEFAULT ''''';
                      EXECUTE 'ALTER TABLE mentorsessions ADD COLUMN IF NOT EXISTS structured_notes jsonb NOT NULL DEFAULT ''{}''::jsonb';
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
            ],
        ),
        migrations.AlterField(
            model_name='mentorsession',
            name='notes',
            field=models.TextField(blank=True, help_text='Basic session notes'),
        ),
        migrations.AlterField(
            model_name='mentorsession',
            name='zoom_url',
            field=models.URLField(blank=True, help_text='Meeting link (Zoom, Google Meet, etc.)'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Idempotent table creation: avoid crashing if these tables already exist.
                # Note: this project uses `users` as the AUTH_USER_MODEL table (BigAutoField PK).
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                      -- sessionattendance
                      EXECUTE '
                        CREATE TABLE IF NOT EXISTS sessionattendance (
                          id uuid PRIMARY KEY,
                          attended boolean NOT NULL DEFAULT false,
                          joined_at timestamptz NULL,
                          left_at timestamptz NULL,
                          created_at timestamptz NOT NULL DEFAULT now(),
                          updated_at timestamptz NOT NULL DEFAULT now(),
                          mentee_id bigint NOT NULL,
                          session_id uuid NOT NULL
                        )
                      ';

                      -- Foreign keys / constraints (idempotent).
                      IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conrelid = 'sessionattendance'::regclass
                          AND conname = 'sessionattendance_mentee_id_fk'
                      ) THEN
                        EXECUTE 'ALTER TABLE sessionattendance
                                 ADD CONSTRAINT sessionattendance_mentee_id_fk
                                 FOREIGN KEY (mentee_id) REFERENCES users(id)
                                 ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED';
                      END IF;

                      IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conrelid = 'sessionattendance'::regclass
                          AND conname = 'sessionattendance_session_id_fk'
                      ) THEN
                        EXECUTE 'ALTER TABLE sessionattendance
                                 ADD CONSTRAINT sessionattendance_session_id_fk
                                 FOREIGN KEY (session_id) REFERENCES mentorsessions(id)
                                 ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED';
                      END IF;

                      IF to_regclass('sessionattendance_session_id_mentee_id_uniq') IS NULL
                         AND NOT EXISTS (
                           SELECT 1
                           FROM pg_constraint
                           WHERE conrelid = 'sessionattendance'::regclass
                             AND conname = 'sessionattendance_session_id_mentee_id_uniq'
                         )
                      THEN
                        EXECUTE 'ALTER TABLE sessionattendance
                                 ADD CONSTRAINT sessionattendance_session_id_mentee_id_uniq
                                 UNIQUE (session_id, mentee_id)';
                      END IF;

                      -- Indexes
                      EXECUTE 'CREATE INDEX IF NOT EXISTS sessionatte_session_6e7a34_idx ON sessionattendance (session_id, attended)';
                      EXECUTE 'CREATE INDEX IF NOT EXISTS sessionatte_mentee__495f19_idx ON sessionattendance (mentee_id, session_id)';

                      -- sessionnotes
                      EXECUTE '
                        CREATE TABLE IF NOT EXISTS sessionnotes (
                          id uuid PRIMARY KEY,
                          key_takeaways jsonb NOT NULL DEFAULT ''[]''::jsonb,
                          action_items jsonb NOT NULL DEFAULT ''[]''::jsonb,
                          discussion_points text NOT NULL DEFAULT '''',
                          next_steps text NOT NULL DEFAULT '''',
                          mentor_reflections text NOT NULL DEFAULT '''',
                          created_at timestamptz NOT NULL DEFAULT now(),
                          updated_at timestamptz NOT NULL DEFAULT now(),
                          session_id uuid NOT NULL
                        )
                      ';
                      IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conrelid = 'sessionnotes'::regclass
                          AND conname = 'sessionnotes_session_id_fk'
                      ) THEN
                        EXECUTE 'ALTER TABLE sessionnotes
                                 ADD CONSTRAINT sessionnotes_session_id_fk
                                 FOREIGN KEY (session_id) REFERENCES mentorsessions(id)
                                 ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED';
                      END IF;

                      IF to_regclass('sessionnotes_session_id_key') IS NULL
                         AND NOT EXISTS (
                           SELECT 1
                           FROM pg_constraint
                           WHERE conrelid = 'sessionnotes'::regclass
                             AND conname = 'sessionnotes_session_id_key'
                         )
                      THEN
                        EXECUTE 'ALTER TABLE sessionnotes
                                 ADD CONSTRAINT sessionnotes_session_id_key
                                 UNIQUE (session_id)';
                      END IF;
                      EXECUTE 'CREATE INDEX IF NOT EXISTS sessionnote_session_4399de_idx ON sessionnotes (session_id)';
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
            ],
        ),
    ]
