# Generated by Django 5.2.9 on 2025-12-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_coordination', '0002_initial'),
    ]

    operations = [
    ]
