# Generated by Django 5.2.9 on 2025-12-19 23:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_coordination', '0002_mentorsession_is_closed_mentorsession_recording_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Idempotent: These columns may already exist from migration 0002
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                      -- These columns may already exist from migration 0002, so use IF NOT EXISTS
                      IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'mentorsessions' AND column_name = 'is_closed'
                      ) THEN
                        ALTER TABLE mentorsessions ADD COLUMN is_closed boolean NOT NULL DEFAULT false;
                      END IF;
                      
                      IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'mentorsessions' AND column_name = 'recording_url'
                      ) THEN
                        ALTER TABLE mentorsessions ADD COLUMN recording_url varchar(200) DEFAULT '';
                      END IF;
                      
                      IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'mentorsessions' AND column_name = 'structured_notes'
                      ) THEN
                        ALTER TABLE mentorsessions ADD COLUMN structured_notes jsonb DEFAULT '{}'::jsonb;
                      END IF;
                      
                      IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'mentorsessions' AND column_name = 'transcript_url'
                      ) THEN
                        ALTER TABLE mentorsessions ADD COLUMN transcript_url varchar(200) DEFAULT '';
                      END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='mentorsession',
                    name='is_closed',
                    field=models.BooleanField(default=False, help_text='Session closed - notes locked'),
                ),
                migrations.AddField(
                    model_name='mentorsession',
                    name='recording_url',
                    field=models.URLField(blank=True, help_text='Session recording URL'),
                ),
                migrations.AddField(
                    model_name='mentorsession',
                    name='structured_notes',
                    field=models.JSONField(blank=True, default=dict, help_text='Structured notes with takeaways, action items, etc.'),
                ),
                migrations.AddField(
                    model_name='mentorsession',
                    name='transcript_url',
                    field=models.URLField(blank=True, help_text='Session transcript URL'),
                ),
            ],
        ),
        # These tables may already exist from migration 0002, so only update Django state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DO $$ BEGIN END $$;",  # Tables already created in migration 0002, no-op
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='SessionAttendance',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('attended', models.BooleanField(default=False)),
                        ('joined_at', models.DateTimeField(blank=True, help_text='When mentee joined the session', null=True)),
                        ('left_at', models.DateTimeField(blank=True, help_text='When mentee left the session', null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to=settings.AUTH_USER_MODEL)),
                        ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='mentorship_coordination.mentorsession')),
                    ],
                    options={
                        'db_table': 'sessionattendance',
                        'indexes': [models.Index(fields=['session', 'attended'], name='sessionatte_session_6e7a34_idx'), models.Index(fields=['mentee', 'session'], name='sessionatte_mentee__495f19_idx')],
                        'unique_together': {('session', 'mentee')},
                    },
                ),
                migrations.CreateModel(
                    name='SessionNotes',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('key_takeaways', models.JSONField(blank=True, default=list, help_text='List of key takeaways')),
                        ('action_items', models.JSONField(blank=True, default=list, help_text='List of action items with assignees')),
                        ('discussion_points', models.TextField(blank=True, help_text='Main discussion points')),
                        ('next_steps', models.TextField(blank=True, help_text='Recommended next steps')),
                        ('mentor_reflections', models.TextField(blank=True, help_text='Mentor reflections on the session')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes_detail', to='mentorship_coordination.mentorsession')),
                    ],
                    options={
                        'db_table': 'sessionnotes',
                        'indexes': [models.Index(fields=['session'], name='sessionnote_session_4399de_idx')],
                    },
                ),
            ],
        ),
    ]
