# Generated by Django 5.2.9 on 2025-12-29 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_coordination', '0003_mentorsession_is_closed_mentorsession_recording_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Overall session rating (1-5)')),
                ('mentor_engagement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Mentor engagement level (1-5)')),
                ('mentor_preparation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Mentor preparation level (1-5)')),
                ('session_value', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Session value/helpfulness (1-5)')),
                ('strengths', models.TextField(blank=True, help_text='What went well')),
                ('areas_for_improvement', models.TextField(blank=True, help_text='Areas for improvement')),
                ('additional_comments', models.TextField(blank=True, help_text='Additional comments')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedback_given', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedback_received', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_records', to='mentorship_coordination.mentorsession')),
            ],
            options={
                'db_table': 'sessionfeedback',
                'indexes': [models.Index(fields=['session', 'mentee'], name='sessionfeed_session_abce82_idx'), models.Index(fields=['mentor'], name='sessionfeed_mentor__6b6df4_idx'), models.Index(fields=['submitted_at'], name='sessionfeed_submitt_eed67e_idx')],
                'unique_together': {('session', 'mentee')},
            },
        ),
    ]
