# Generated by Django 5.2.9 on 2025-12-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_coordination', '0004_add_session_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorsession',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation'),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='Session was cancelled'),
        ),
    ]
