# Generated by Django 5.2.9 on 2026-01-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_coordination', '0005_add_cancelled_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorsession',
            name='feedback_comment',
            field=models.TextField(blank=True, help_text='Student feedback comments'),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='feedback_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], help_text='Student rating (1-5 stars)', null=True),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='feedback_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When feedback was submitted', null=True),
        ),
    ]
