# Generated by Django 5.2.9 on 2026-01-06 12:25

import django.db.models.deletion
import mentorship_coordination.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_coordination', '0006_mentorsession_feedback_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorsession',
            name='feedback_comment',
        ),
        migrations.RemoveField(
            model_name='mentorsession',
            name='feedback_rating',
        ),
        migrations.RemoveField(
            model_name='mentorsession',
            name='feedback_submitted_at',
        ),
        migrations.CreateModel(
            name='MentorshipMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(db_index=True, help_text='Unique message identifier', max_length=100, unique=True)),
                ('subject', models.CharField(blank=True, help_text='Message subject (optional)', max_length=200)),
                ('body', models.TextField(help_text='Message content')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(db_index=True, default=False, help_text='Message archived after mentorship closure')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(help_text='Mentor-mentee assignment this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mentorship_coordination.menteementorassignment')),
                ('recipient', models.ForeignKey(help_text='User who receives the message', on_delete=django.db.models.deletion.CASCADE, related_name='received_mentorship_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_mentorship_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentorshipmessages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Attached file', upload_to=mentorship_coordination.models.upload_message_attachment)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(help_text='MIME type', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mentorship_coordination.mentorshipmessage')),
            ],
            options={
                'db_table': 'messageattachments',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_id', models.CharField(db_index=True, help_text='Unique notification identifier', max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('session_reminder', 'Session Reminder'), ('feedback_reminder', 'Feedback Reminder'), ('milestone_achieved', 'Milestone Achieved'), ('session_cancelled', 'Session Cancelled'), ('session_rescheduled', 'Session Rescheduled'), ('assignment_started', 'Assignment Started'), ('assignment_completed', 'Assignment Completed'), ('custom', 'Custom Notification')], db_index=True, max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App'), ('push', 'Push Notification')], db_index=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When notification was delivered', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if notification failed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (template_id, provider, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assignment', models.ForeignKey(blank=True, help_text='Mentor-mentee assignment (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mentorship_coordination.menteementorassignment')),
                ('recipient', models.ForeignKey(help_text='User who receives the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, help_text='Related session (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentorship_coordination.mentorsession')),
            ],
            options={
                'db_table': 'notificationlogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mentorshipmessage',
            index=models.Index(fields=['assignment', 'created_at'], name='mentorshipm_assignm_78075e_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipmessage',
            index=models.Index(fields=['sender', 'recipient', 'archived'], name='mentorshipm_sender__07ee15_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipmessage',
            index=models.Index(fields=['is_read', 'created_at'], name='mentorshipm_is_read_ca57c6_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message'], name='messageatta_message_60ade2_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_4ec25a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification_type', 'status'], name='notificatio_notific_c3c0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['assignment', 'created_at'], name='notificatio_assignm_a3ec51_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['session', 'created_at'], name='notificatio_session_7cc27a_idx'),
        ),
    ]
