# Generated by Django 5.2.9 on 2026-01-07 18:04

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('orientation', 'Orientation'), ('mentorship', 'Mentorship'), ('session', 'Session'), ('project_review', 'Project Review'), ('submission', 'Submission'), ('holiday', 'Holiday'), ('closure', 'Closure')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_ts', models.DateTimeField()),
                ('end_ts', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for the event', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('milestone_id', models.UUIDField(blank=True, help_text='Reference to milestone if this is a milestone event', null=True)),
                ('completion_tracked', models.BooleanField(default=False, help_text='Whether completion is tracked for this event')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['start_ts'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_uri', models.URLField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('mode', models.CharField(choices=[('onsite', 'Onsite'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='virtual', max_length=20)),
                ('seat_cap', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mentor_ratio', models.FloatField(default=0.1, help_text='Mentors per student ratio', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('calendar_id', models.UUIDField(blank=True, null=True)),
                ('calendar_template_id', models.UUIDField(blank=True, help_text='Reference to calendar template used', null=True)),
                ('seat_pool', models.JSONField(blank=True, default=dict, help_text='Seat pool breakdown: {paid: count, scholarship: count, sponsored: count}')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('running', 'Running'), ('closing', 'Closing'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cohorts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DirectorCohortDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort_name', models.CharField(max_length=200)),
                ('track_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('onsite', 'Onsite'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='virtual', max_length=20)),
                ('seats_total', models.IntegerField(default=0)),
                ('seats_used', models.IntegerField(default=0)),
                ('seats_scholarship', models.IntegerField(default=0)),
                ('seats_sponsored', models.IntegerField(default=0)),
                ('enrollment_status', models.JSONField(default=dict, help_text='{active: 45, pending: 3, withdrawn: 2}')),
                ('readiness_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('completion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentor_coverage_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentor_session_completion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mission_approval_time_avg', models.IntegerField(blank=True, null=True)),
                ('portfolio_health_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('at_risk_mentees', models.IntegerField(default=0)),
                ('milestones_upcoming', models.JSONField(default=list, help_text='List of next milestone events with dates')),
                ('calendar_events', models.JSONField(default=list, help_text='Upcoming key dates')),
                ('flags_active', models.JSONField(default=list, help_text='Cohort or mentor risk flags')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'director_cohort_dashboard',
                'ordering': ['-updated_at'],
            },
        ),
    ]
