# Generated by Django 5.2.9 on 2025-12-04 16:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('leadership', 'Leadership'), ('mentorship', 'Mentorship'), ('executive', 'Executive')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('default_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('outcomes', models.JSONField(blank=True, default=list, help_text='List of learning outcomes and goals')),
                ('structure', models.JSONField(blank=True, default=dict, help_text='Default structure with modules and milestones')),
                ('missions_registry_link', models.URLField(blank=True, help_text='Link to Missions/Competency registry')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('mode', models.CharField(choices=[('onsite', 'Onsite'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='virtual', max_length=20)),
                ('seat_cap', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mentor_ratio', models.FloatField(default=0.1, help_text='Mentors per student ratio', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('calendar_id', models.UUIDField(blank=True, null=True)),
                ('calendar_template_id', models.UUIDField(blank=True, help_text='Reference to calendar template used', null=True)),
                ('seat_pool', models.JSONField(blank=True, default=dict, help_text='Seat pool breakdown: {paid: count, scholarship: count, sponsored: count}')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('running', 'Running'), ('closing', 'Closing'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, help_text='Program coordinator for this cohort', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_cohorts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cohorts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('orientation', 'Orientation'), ('mentorship', 'Mentorship'), ('session', 'Session'), ('project_review', 'Project Review'), ('submission', 'Submission'), ('holiday', 'Holiday'), ('closure', 'Closure')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_ts', models.DateTimeField()),
                ('end_ts', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for the event', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('milestone_id', models.UUIDField(blank=True, help_text='Reference to milestone if this is a milestone event', null=True)),
                ('completion_tracked', models.BooleanField(default=False, help_text='Whether completion is tracked for this event')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='programs.cohort')),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['start_ts'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_type', models.CharField(choices=[('self', 'Self-enroll'), ('sponsor', 'Sponsor assign'), ('invite', 'Invite'), ('director', 'Director assign')], default='self', max_length=20)),
                ('seat_type', models.CharField(choices=[('paid', 'Paid'), ('scholarship', 'Scholarship'), ('sponsored', 'Sponsored')], default='paid', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed'), ('incomplete', 'Incomplete')], default='pending_payment', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='programs.cohort')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrollments',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_uri', models.URLField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='programs.enrollment')),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('support', 'Support'), ('guest', 'Guest')], default='support', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='programs.cohort')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentor_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule', models.JSONField(default=dict, help_text='{criteria: {attendance_percent: 80, portfolio_approved: true, feedback_score: 4.0, payment_complete: true}, thresholds: {...}, dependencies: [...]}')),
                ('version', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='programs.program')),
            ],
            options={
                'db_table': 'program_rules',
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('competencies', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_tracks', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='programs.program')),
            ],
            options={
                'db_table': 'tracks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('missions', models.JSONField(blank=True, default=list)),
                ('duration_weeks', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='programs.track')),
            ],
            options={
                'db_table': 'specializations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cohort',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='programs.track'),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(help_text='Position in queue (1-based, FIFO)')),
                ('seat_type', models.CharField(choices=[('paid', 'Paid'), ('scholarship', 'Scholarship'), ('sponsored', 'Sponsored')], default='paid', max_length=20)),
                ('enrollment_type', models.CharField(choices=[('self', 'Self-enroll'), ('sponsor', 'Sponsor assign'), ('invite', 'Invite'), ('director', 'Director assign')], default='self', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, help_text='When user was notified of seat availability', null=True)),
                ('promoted_at', models.DateTimeField(blank=True, help_text='When user was promoted from waitlist', null=True)),
                ('active', models.BooleanField(default=True, help_text='False if user was promoted or removed')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='programs.cohort')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waitlist',
                'ordering': ['position', 'added_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('payment_status', 'paid'), ('status', 'pending_payment'), _negated=True), name='pending_payment_requires_pending_payment_status'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('cohort', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='mentorassignment',
            unique_together={('cohort', 'mentor')},
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('program', 'key')},
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['cohort', 'active', 'position'], name='waitlist_cohort__b67570_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waitlist',
            unique_together={('cohort', 'user', 'active')},
        ),
    ]
