# Generated by Django 5.2.9 on 2025-12-04 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='Program coordinator for this cohort', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_cohorts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='programs.cohort'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='programs.cohort'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='programs.enrollment'),
        ),
        migrations.AddField(
            model_name='mentorassignment',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='programs.cohort'),
        ),
        migrations.AddField(
            model_name='mentorassignment',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_mentor_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programrule',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='programs.program'),
        ),
        migrations.AddField(
            model_name='track',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='track',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='programs.program'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='programs.track'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='programs.track'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='programs.cohort'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('payment_status', 'paid'), ('status', 'pending_payment'), _negated=True), name='pending_payment_requires_pending_payment_status'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('cohort', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='mentorassignment',
            unique_together={('cohort', 'mentor')},
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('program', 'key')},
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['cohort', 'active', 'position'], name='waitlist_cohort__b67570_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waitlist',
            unique_together={('cohort', 'user', 'active')},
        ),
    ]
