# Generated by Django 5.2.9 on 2026-01-02 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_add_categories_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_weeks', models.PositiveIntegerField(default=12, help_text='Total duration of the mentorship cycle in weeks')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('milestones', models.JSONField(blank=True, default=list, help_text='List of milestone descriptions')),
                ('goals', models.JSONField(blank=True, default=list, help_text='List of learning goals')),
                ('program_type', models.CharField(choices=[('builders', 'Builders'), ('leaders', 'Leaders'), ('custom', 'Custom')], default='builders', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_cycle', to='programs.cohort')),
            ],
            options={
                'db_table': 'mentorship_cycles',
                'ordering': ['-created_at'],
            },
        ),
    ]
