# Generated by Django 5.2.9 on 2025-12-05 07:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20251204_1936'),
        ('users', '0003_add_profile_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorDashboardCache',
            fields=[
                ('director', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='director_dashboard_cache', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('active_programs_count', models.IntegerField(default=0)),
                ('active_cohorts_count', models.IntegerField(default=0)),
                ('total_seats', models.IntegerField(default=0)),
                ('seats_used', models.IntegerField(default=0)),
                ('seats_pending', models.IntegerField(default=0)),
                ('avg_readiness_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_portfolio_health', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_mission_approval_time_minutes', models.IntegerField(blank=True, null=True)),
                ('mentor_coverage_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentor_session_completion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentors_over_capacity_count', models.IntegerField(default=0)),
                ('mentee_at_risk_count', models.IntegerField(default=0)),
                ('cohorts_flagged_count', models.IntegerField(default=0)),
                ('mentors_flagged_count', models.IntegerField(default=0)),
                ('missions_bottlenecked_count', models.IntegerField(default=0)),
                ('payments_overdue_count', models.IntegerField(default=0)),
                ('cache_updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'director_dashboard_cache',
                'ordering': ['-cache_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectorCohortDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort_name', models.CharField(max_length=200)),
                ('track_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('onsite', 'Onsite'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='virtual', max_length=20)),
                ('seats_total', models.IntegerField(default=0)),
                ('seats_used', models.IntegerField(default=0)),
                ('seats_scholarship', models.IntegerField(default=0)),
                ('seats_sponsored', models.IntegerField(default=0)),
                ('enrollment_status', models.JSONField(default=dict, help_text='{active: 45, pending: 3, withdrawn: 2}')),
                ('readiness_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('completion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentor_coverage_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentor_session_completion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mission_approval_time_avg', models.IntegerField(blank=True, null=True)),
                ('portfolio_health_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('at_risk_mentees', models.IntegerField(default=0)),
                ('milestones_upcoming', models.JSONField(default=list, help_text='List of next milestone events with dates')),
                ('calendar_events', models.JSONField(default=list, help_text='Upcoming key dates')),
                ('flags_active', models.JSONField(default=list, help_text='Cohort or mentor risk flags')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_dashboards', to='programs.cohort')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_cohort_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'director_cohort_dashboard',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['director', 'cohort'], name='idx_director_cohort'), models.Index(fields=['updated_at'], name='idx_cohort_dashboard_updated')],
                'unique_together': {('director', 'cohort')},
            },
        ),
    ]
