# Generated by Django 5.2.9 on 2025-12-13 14:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Mission code like "SIEM-03"', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('capstone', 'Capstone')], db_index=True, max_length=20)),
                ('type', models.CharField(choices=[('lab', 'Lab'), ('scenario', 'Scenario'), ('project', 'Project'), ('capstone', 'Capstone')], db_index=True, default='lab', max_length=20)),
                ('track_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('track_key', models.CharField(blank=True, db_index=True, help_text='Track key like "soc_analyst"', max_length=50)),
                ('est_hours', models.IntegerField(blank=True, help_text='Estimated hours to complete', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('estimated_time_minutes', models.IntegerField(blank=True, help_text='Estimated minutes to complete', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('competencies', models.JSONField(blank=True, default=list, help_text='["SIEM", "Alerting", "IR"]')),
                ('requirements', models.JSONField(blank=True, default=dict, help_text='Mission requirements template, file types, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'missions',
                'indexes': [models.Index(fields=['difficulty', 'track_id'], name='missions_difficu_85295d_idx'), models.Index(fields=['track_key', 'difficulty'], name='missions_track_k_37486a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MissionSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('ai_reviewed', 'AI Reviewed'), ('in_ai_review', 'In AI Review'), ('mentor_review', 'Mentor Review'), ('in_mentor_review', 'In Mentor Review'), ('approved', 'Approved'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('revised', 'Revised')], db_index=True, default='draft', max_length=20)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI review score 0-100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentor_score', models.DecimalField(blank=True, decimal_places=2, help_text='Mentor review score 0-100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_feedback', models.TextField(blank=True)),
                ('mentor_feedback', models.TextField(blank=True, help_text='Premium tier only')),
                ('notes', models.TextField(blank=True, help_text='Student notes to reviewer')),
                ('portfolio_item_id', models.UUIDField(blank=True, help_text='Auto-linked on approval', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ai_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('mentor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='missions.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mission_submissions',
            },
        ),
        migrations.CreateModel(
            name='MissionArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('file', 'File'), ('github', 'GitHub'), ('notebook', 'Notebook'), ('video', 'Video'), ('screenshot', 'Screenshot')], db_index=True, max_length=20)),
                ('url', models.URLField(help_text='S3 signed URL, GitHub link, or video URL', max_length=500)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='missions.missionsubmission')),
            ],
            options={
                'db_table': 'mission_artifacts',
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, help_text='AI score 0-100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('strengths', models.JSONField(blank=True, default=list, help_text='List of strengths')),
                ('gaps', models.JSONField(blank=True, default=list, help_text='List of gaps')),
                ('suggestions', models.JSONField(blank=True, default=list, help_text='List of suggestions')),
                ('competencies_detected', models.JSONField(blank=True, default=list, help_text='Detected competencies with levels')),
                ('full_feedback', models.JSONField(blank=True, default=dict, help_text='Structured feedback (correctness, missed_requirements, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback_detail', to='missions.missionsubmission')),
            ],
            options={
                'db_table': 'ai_feedback',
            },
        ),
        migrations.AddIndex(
            model_name='missionsubmission',
            index=models.Index(fields=['user', 'status'], name='mission_sub_user_id_fc6b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='missionsubmission',
            index=models.Index(fields=['mission', 'status'], name='mission_sub_mission_18452d_idx'),
        ),
        migrations.AddIndex(
            model_name='missionsubmission',
            index=models.Index(fields=['user', 'mission'], name='mission_sub_user_id_103dc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='missionsubmission',
            unique_together={('mission', 'user')},
        ),
        migrations.AddIndex(
            model_name='missionartifact',
            index=models.Index(fields=['submission', 'type'], name='mission_art_submiss_c3fba2_idx'),
        ),
        migrations.AddIndex(
            model_name='missionartifact',
            index=models.Index(fields=['submission', 'created_at'], name='mission_art_submiss_072bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['submission'], name='ai_feedback_submiss_c7f4b4_idx'),
        ),
    ]
