# Generated by Django 4.2.26 on 2025-12-04 07:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('capstone', 'Capstone')], db_index=True, max_length=20)),
                ('track_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('est_hours', models.IntegerField(blank=True, help_text='Estimated hours to complete', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('competencies', models.JSONField(blank=True, default=list, help_text='["networking", "dfir", "python"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'missions',
            },
        ),
        migrations.CreateModel(
            name='MissionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_url', models.URLField(help_text='S3 signed URL or local path', max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'missionfiles',
            },
        ),
        migrations.CreateModel(
            name='MissionSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('ai_reviewed', 'AI Reviewed'), ('mentor_review', 'Mentor Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI review score 0-100', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_feedback', models.TextField(blank=True)),
                ('mentor_feedback', models.TextField(blank=True, help_text='Premium tier only')),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='missions.mission')),
            ],
            options={
                'db_table': 'missionsubmissions',
            },
        ),
    ]
