# Generated by Django 5.2.9 on 2025-12-04 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='missionsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missionfile',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='missions.missionsubmission'),
        ),
        migrations.AddIndex(
            model_name='missionsubmission',
            index=models.Index(fields=['user', 'status'], name='missionsubm_user_id_c21d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='missionsubmission',
            index=models.Index(fields=['mission', 'status'], name='missionsubm_mission_525c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='missionfile',
            index=models.Index(fields=['submission', 'uploaded_at'], name='missionfile_submiss_2e4225_idx'),
        ),
    ]
