# Generated by Django 5.2.9 on 2025-12-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_fix_legacy_submission_tables'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # DB drift support:
                # - Some DBs already have `kind` (created by 0004_fix_legacy_submission_tables).
                # - Some DBs still have legacy `type` + its index (created by 0001_initial).
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                      -- Drop legacy index (submission,type) if present.
                      EXECUTE 'DROP INDEX IF EXISTS mission_art_submiss_c3fba2_idx';

                      -- Ensure `kind` exists and is populated.
                      IF NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'mission_artifacts'
                          AND column_name = 'kind'
                      ) THEN
                        EXECUTE 'ALTER TABLE mission_artifacts ADD COLUMN kind varchar(20)';

                        -- Prefer migrating values from legacy `type` when available.
                        IF EXISTS (
                          SELECT 1
                          FROM information_schema.columns
                          WHERE table_schema = current_schema()
                            AND table_name = 'mission_artifacts'
                            AND column_name = 'type'
                        ) THEN
                          EXECUTE 'UPDATE mission_artifacts SET kind = type WHERE kind IS NULL';
                        ELSE
                          EXECUTE 'UPDATE mission_artifacts SET kind = ''file'' WHERE kind IS NULL';
                        END IF;

                        EXECUTE 'ALTER TABLE mission_artifacts ALTER COLUMN kind SET NOT NULL';
                      END IF;

                      -- Drop legacy `type` column if present.
                      IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name = 'mission_artifacts'
                          AND column_name = 'type'
                      ) THEN
                        EXECUTE 'ALTER TABLE mission_artifacts DROP COLUMN type';
                      END IF;

                      -- Create the new index (submission,kind).
                      EXECUTE 'CREATE INDEX IF NOT EXISTS mission_art_submiss_7b7a76_idx ON mission_artifacts (submission_id, kind)';
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
        migrations.RemoveIndex(
            model_name='missionartifact',
            name='mission_art_submiss_c3fba2_idx',
        ),
        migrations.RemoveField(
            model_name='missionartifact',
            name='type',
        ),
        migrations.AddField(
            model_name='missionartifact',
            name='kind',
                    field=models.CharField(
                        choices=[('file', 'File'), ('github', 'GitHub'), ('notebook', 'Notebook'), ('video', 'Video'), ('screenshot', 'Screenshot')],
                        db_index=True,
                        default='file',
                        help_text='Type of artifact',
                        max_length=20,
                    ),
            preserve_default=False,
                ),
                migrations.AddIndex(
                    model_name='missionartifact',
                    index=models.Index(fields=['submission', 'kind'], name='mission_art_submiss_7b7a76_idx'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='missionsubmission',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('ai_reviewed', 'AI Reviewed'), ('in_ai_review', 'In AI Review'), ('mentor_review', 'Mentor Review'), ('in_mentor_review', 'In Mentor Review'), ('approved', 'Approved'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('revised', 'Revised')], db_index=True, default='not_started', max_length=20),
        ),
    ]
