# Generated by Django 5.2.9 on 2025-12-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_add_mxp_models'),
        ('missions', '0004_fix_legacy_submission_tables'),
    ]

    operations = [
    ]
