# Generated by Django 5.2.9 on 2025-12-19 17:38

import django.core.validators
from django.db import migrations, models


def rename_type_to_kind_conditionally(apps, schema_editor):
    """Conditionally rename type column to kind if type exists."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if type column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'mission_artifacts' 
            AND column_name = 'type'
        """)
        type_exists = cursor.fetchone() is not None
        
        # Check if kind column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'mission_artifacts' 
            AND column_name = 'kind'
        """)
        kind_exists = cursor.fetchone() is not None
        
        # Only rename if type exists and kind doesn't
        if type_exists and not kind_exists:
            cursor.execute("ALTER TABLE mission_artifacts RENAME COLUMN type TO kind")
        elif not type_exists and kind_exists:
            # Already renamed, do nothing
            pass
        elif type_exists and kind_exists:
            # Both exist - drop type (shouldn't happen but handle it)
            cursor.execute("ALTER TABLE mission_artifacts DROP COLUMN type")


def reverse_rename_kind_to_type(apps, schema_editor):
    """Reverse: rename kind back to type if needed."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'mission_artifacts' 
            AND column_name = 'kind'
        """)
        if cursor.fetchone() is not None:
            cursor.execute("ALTER TABLE mission_artifacts RENAME COLUMN kind TO type")


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_merge_20251219_1730'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='missionartifact',
            name='mission_art_submiss_c3fba2_idx',
        ),
        migrations.RenameIndex(
            model_name='missionfile',
            new_name='mission_fil_mission_46f0df_idx',
            old_name='mission_fil_mission_subtask_idx',
        ),
        migrations.RenameIndex(
            model_name='missionfile',
            new_name='mission_fil_mission_6b92ae_idx',
            old_name='mission_fil_mission_uploaded_idx',
        ),
        migrations.RenameIndex(
            model_name='missionprogress',
            new_name='mission_pro_user_id_1708b3_idx',
            old_name='mission_pro_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='missionprogress',
            new_name='mission_pro_mission_5557d6_idx',
            old_name='mission_pro_mission_status_idx',
        ),
        migrations.RenameIndex(
            model_name='missionprogress',
            new_name='mission_pro_user_id_6db1cc_idx',
            old_name='mission_pro_user_id_mission_idx',
        ),
        migrations.RenameIndex(
            model_name='missionprogress',
            new_name='mission_pro_user_id_ddb499_idx',
            old_name='mission_pro_user_id_final_status_idx',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='estimated_time_minutes',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mission',
            name='estimated_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Estimated minutes to complete', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    rename_type_to_kind_conditionally,
                    reverse_rename_kind_to_type
                ),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='missionartifact',
                    old_name='type',
                    new_name='kind',
                ),
            ]
        ),
        migrations.AlterField(
            model_name='mission',
            name='difficulty',
            field=models.CharField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('elite', 'Elite')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='est_hours',
            field=models.IntegerField(blank=True, help_text='Estimated hours to complete (legacy)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mission',
            name='tier',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mastery', 'Mastery'), ('capstone', 'Capstone')], db_index=True, help_text='Tier: beginner, intermediate, advanced, mastery, capstone', max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='track',
            field=models.CharField(choices=[('defender', 'Defender'), ('offensive', 'Offensive'), ('grc', 'GRC'), ('innovation', 'Innovation'), ('leadership', 'Leadership')], db_index=True, help_text='Track: defender, offensive, grc, innovation, leadership', max_length=20),
        ),
        migrations.AlterField(
            model_name='missionsubmission',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('ai_reviewed', 'AI Reviewed'), ('in_ai_review', 'In AI Review'), ('mentor_review', 'Mentor Review'), ('in_mentor_review', 'In Mentor Review'), ('approved', 'Approved'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('revised', 'Revised')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE INDEX IF NOT EXISTS mission_art_submiss_7b7a76_idx 
                    ON mission_artifacts (submission_id, kind);
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS mission_art_submiss_7b7a76_idx;
                    """
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='missionartifact',
                    index=models.Index(fields=['submission', 'kind'], name='mission_art_submiss_7b7a76_idx'),
                ),
            ]
        ),
    ]
