# Generated by Django 5.2.8 on 2025-12-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_add_mxp_models'),
        ('missions', '0005_remove_missionartifact_mission_art_submiss_c3fba2_idx_and_more'),
    ]

    operations = [
    ]
