# Generated by Django 5.2.9 on 2025-12-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_remove_missionartifact_mission_art_submiss_c3fba2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionartifact',
            name='kind',
            field=models.CharField(choices=[('file', 'File'), ('github', 'GitHub'), ('notebook', 'Notebook'), ('video', 'Video'), ('screenshot', 'Screenshot')], db_index=True, default='file', help_text='Type of artifact', max_length=20),
        ),
    ]
