# Generated by Django 5.2.8 on 2025-12-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_merge_20251220_0318'),
        ('missions', '0007_alter_missionartifact_kind'),
    ]

    operations = [
    ]
