# Generated by Django 5.2.9 on 2025-12-20 08:56

from django.db import migrations


def ensure_kind_field_state(apps, schema_editor):
    """Ensure the state has 'kind' field, not 'type' - database is already correct."""
    # This is a no-op for database, just ensures state is correct
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_alter_missionartifact_kind'),
        ('missions', '0009_fix_all_legacy_columns_constraints'),
    ]

    operations = [
        # This merge migration reconciles two branches:
        # - Branch 1: 0007_alter_missionartifact_kind (expects 'kind' field)
        # - Branch 2: 0009_fix_all_legacy_columns_constraints (doesn't touch missionartifact)
        # Both branches have been applied, database is correct
        # The state should already be correct after processing both branches
        # No operations needed - this is just a merge point
    ]
