# Generated by Django 5.2.9 on 2025-12-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_merge_20251220_0318'),
        ('missions', '0010_merge_20251220_0856'),
    ]

    operations = [
    ]
