# Generated by Django 5.2.9 on 2025-12-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_merge_20251221_1125'),
        ('missions', '0011_merge_20251221_1828'),
    ]

    operations = [
    ]
