# Generated by Django 5.2.8 on 2025-12-03 19:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('learn', 'Learn'), ('practice', 'Practice'), ('reflect', 'Reflect')], max_length=20)),
                ('target_frequency', models.IntegerField(default=1, help_text='Times per week', validators=[django.core.validators.MinValueValidator(1)])),
                ('streak_current', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('streak_longest', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habits',
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='coaching.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habitlogs',
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI computed -0.5 to +0.5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(-0.5), django.core.validators.MaxValueValidator(0.5)])),
                ('behavior_tags', models.JSONField(blank=True, default=list, help_text='["discipline", "growth_mindset"]')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reflections',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('overdue', 'Overdue')], db_index=True, default='active', max_length=20)),
                ('target_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mentor_feedback', models.TextField(blank=True, help_text='Premium tier only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goals',
                'indexes': [models.Index(fields=['user', 'status'], name='goals_user_id_49fd29_idx'), models.Index(fields=['user', 'target_date'], name='goals_user_id_8cf4d7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'created_at'], name='habits_user_id_1b4ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['user', 'completed_at'], name='habitlogs_user_id_77d382_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', 'completed_at'], name='habitlogs_habit_i_634629_idx'),
        ),
        migrations.AddConstraint(
            model_name='habitlog',
            constraint=models.UniqueConstraint(condition=models.Q(('completed_at__date', models.F('completed_at__date'))), fields=('habit',), name='unique_habit_per_day'),
        ),
        migrations.AddIndex(
            model_name='reflection',
            index=models.Index(fields=['user', 'created_at'], name='reflections_user_id_601024_idx'),
        ),
    ]
