# Generated by Django 5.2.9 on 2025-12-04 19:34

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('overdue', 'Overdue')], db_index=True, default='active', max_length=20)),
                ('target_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mentor_feedback', models.TextField(blank=True, help_text='Premium tier only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'goals',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('learn', 'Learn'), ('practice', 'Practice'), ('reflect', 'Reflect')], max_length=20)),
                ('target_frequency', models.IntegerField(default=1, help_text='Times per week', validators=[django.core.validators.MinValueValidator(1)])),
                ('streak_current', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('streak_longest', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'habits',
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'habitlogs',
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI computed -0.5 to +0.5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(-0.5), django.core.validators.MaxValueValidator(0.5)])),
                ('behavior_tags', models.JSONField(blank=True, default=list, help_text='["discipline", "growth_mindset"]')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'reflections',
            },
        ),
    ]
