# Generated by Django 5.2.9 on 2025-12-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_update_habitlog_and_reflection'),
        ('coaching', '0003_add_rls_policies'),
    ]

    operations = [
    ]
