# Generated by Django 5.2.8 on 2025-12-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0004_fix_habitlog_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habitlog',
            name='unique_habit_per_day',
        ),
    ]
