# Generated by Django 5.2.9 on 2025-12-17 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0004_merge_20251214_1645'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='habitlog',
            name='habitlogs_user_id_77d382_idx',
        ),
        migrations.RemoveIndex(
            model_name='habitlog',
            name='habitlogs_habit_i_634629_idx',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='mentor_feedback',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='type',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='last_completed_at',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='streak_current',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='streak_longest',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='target_frequency',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='behavior_tags',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='response',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='sentiment_score',
        ),
        migrations.AddField(
            model_name='goal',
            name='scope',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Daily or weekly frequency', max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_core',
            field=models.BooleanField(default=False, help_text='Learn/Practice/Reflect = True'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='ai_sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], help_text='AI computed sentiment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reflection',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list, help_text='["overwhelmed", "confident"]'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together={('habit', 'log_date')},
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['user', 'log_date'], name='habitlogs_user_id_b1ad3e_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', 'log_date'], name='habitlogs_habit_i_fda112_idx'),
        ),
    ]
