# Generated by Django 5.2.9 on 2025-12-17 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0004_merge_20251214_1645'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Skip removing indices that may not exist - they were likely removed in previous migrations
        # migrations.RemoveIndex(
        #     model_name='habitlog',
        #     name='habitlogs_user_id_77d382_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='habitlog',
        #     name='habitlogs_habit_i_634629_idx',
        # ),
        # Note: completed_at, target_date, and last_completed_at removals are handled conditionally in migration 0006
        # We skip removing them here to avoid conflicts
        migrations.RemoveField(
            model_name='goal',
            name='mentor_feedback',
        ),
        # Note: type field is kept in Goal model, so we don't remove it
        # The scope field added below might conflict with 0006, but 0006 handles it
        # Note: category, streak_current, streak_longest, and target_frequency 
        # were renamed in 0005_add_coaching_os_models to type, streak, longest_streak, and frequency
        # These fields don't need to be removed as they've been renamed
        # If the old fields still exist in the database, migration 0006 will handle them conditionally
        # Note: behavior_tags, response, and sentiment_score are handled in migration 0006
        # behavior_tags -> emotion_tags, sentiment_score -> sentiment in 0006
        # We skip removing them here to avoid conflicts
        # Note: scope field addition removed - conflicts with 0006 which keeps type field
        # migrations.AddField(
        #     model_name='goal',
        #     name='scope',
        #     field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default=1, max_length=20),
        #     preserve_default=False,
        # ),
        # Skip adding fields that may already exist
        # migrations.AddField(
        #     model_name='habit',
        #     name='frequency',
        #     field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Daily or weekly frequency', max_length=20),
        # ),
        # migrations.AddField(
        #     model_name='habit',
        #     name='is_core',
        #     field=models.BooleanField(default=False, help_text='Learn/Practice/Reflect = True'),
        # ),
        # Skip adding reflection fields that may already exist
        # migrations.AddField(
        #     model_name='reflection',
        #     name='ai_sentiment',
        #     field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], help_text='AI computed sentiment', max_length=20, null=True),
        # ),
        # migrations.AddField(
        #     model_name='reflection',
        #     name='ai_tags',
        #     field=models.JSONField(blank=True, default=list, help_text='["overwhelmed", "confident"]'),
        # ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together={('habit', 'date')},
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['user', 'date'], name='habitlogs_user_id_b1ad3e_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', 'date'], name='habitlogs_habit_i_fda112_idx'),
        ),
    ]
