# Generated by Django 5.2.8 on 2025-12-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0005_add_coaching_os_models'),
        ('coaching', '0005_remove_habitlog_habitlogs_user_id_77d382_idx_and_more'),
    ]

    operations = [
    ]
