# Generated by Django 5.2.9 on 2025-12-19 17:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_goal_completed_at_conditionally(apps, schema_editor):
    """Conditionally remove completed_at column from goals if it exists."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check which table name exists
        cursor.execute("""
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_name IN ('goals', 'coaching_goals')
            AND table_schema = 'public'
        """)
        table_result = cursor.fetchone()
        if not table_result:
            return
        
        table_name = table_result[0]
        
        # Check if completed_at column exists
        cursor.execute(f"""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = '{table_name}' 
            AND column_name = 'completed_at'
        """)
        if cursor.fetchone() is not None:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN completed_at")


def reverse_remove_goal_completed_at(apps, schema_editor):
    """Reverse: add completed_at back (optional, can be no-op)."""
    pass


def remove_goal_target_date_conditionally(apps, schema_editor):
    """Conditionally remove target_date column from goals if it exists."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check which table name exists
        cursor.execute("""
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_name IN ('goals', 'coaching_goals')
            AND table_schema = 'public'
        """)
        table_result = cursor.fetchone()
        if not table_result:
            return
        
        table_name = table_result[0]
        
        # Check if target_date column exists
        cursor.execute(f"""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = '{table_name}' 
            AND column_name = 'target_date'
        """)
        if cursor.fetchone() is not None:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN target_date")


def reverse_remove_goal_target_date(apps, schema_editor):
    """Reverse: add target_date back (optional, can be no-op)."""
    pass


def remove_habit_last_completed_at_conditionally(apps, schema_editor):
    """Conditionally remove last_completed_at column from habits if it exists."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check which table name exists
        cursor.execute("""
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_name IN ('habits', 'coaching_habits')
            AND table_schema = 'public'
        """)
        table_result = cursor.fetchone()
        if not table_result:
            return
        
        table_name = table_result[0]
        
        # Check if last_completed_at column exists
        cursor.execute(f"""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = '{table_name}' 
            AND column_name = 'last_completed_at'
        """)
        if cursor.fetchone() is not None:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN last_completed_at")


def reverse_remove_habit_last_completed_at(apps, schema_editor):
    """Reverse: add last_completed_at back (optional, can be no-op)."""
    pass


def alter_goal_fields_conditionally(apps, schema_editor):
    """Conditionally alter goal fields - add if missing, alter if exists."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check which table name exists
        cursor.execute("""
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_name IN ('goals', 'coaching_goals')
            AND table_schema = 'public'
        """)
        table_result = cursor.fetchone()
        if not table_result:
            return
        
        table_name = table_result[0]
        
        # Check if type column exists - if not, it might have been created with a different name
        cursor.execute(f"""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = '{table_name}' 
            AND column_name = 'type'
        """)
        if cursor.fetchone() is None:
            # Type column doesn't exist - might need to add it
            # But this is likely already handled by migration 0005, so we'll skip
            pass
        
        # Fields to check and add if missing
        fields_to_add = [
            ('mentor_feedback', 'TEXT'),
            ('subscription_tier', 'VARCHAR(20)'),
            ('due_date', 'DATE'),
            ('updated_at', 'TIMESTAMP WITH TIME ZONE DEFAULT NOW()'),
            ('progress', 'INTEGER DEFAULT 0'),
            ('target', 'INTEGER DEFAULT 1'),
            ('current', 'INTEGER DEFAULT 0'),
        ]
        
        for field_name, field_type in fields_to_add:
            cursor.execute(f"""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = '{table_name}' 
                AND column_name = '{field_name}'
            """)
            if cursor.fetchone() is None:
                # Add the column if it doesn't exist
                try:
                    cursor.execute(f"""
                        ALTER TABLE {table_name} 
                        ADD COLUMN {field_name} {field_type}
                    """)
                except Exception as e:
                    # Ignore errors if column already exists or other issues
                    pass


def reverse_alter_goal_fields(apps, schema_editor):
    """Reverse: optional, can be no-op."""
    pass


def alter_reflection_fields_conditionally(apps, schema_editor):
    """Conditionally alter reflection fields - add if missing, rename if needed."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check which table name exists
        cursor.execute("""
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_name IN ('reflections', 'coaching_reflections')
            AND table_schema = 'public'
        """)
        table_result = cursor.fetchone()
        if not table_result:
            return
        
        table_name = table_result[0]
        
        # Check for sentiment column - might be sentiment_score or ai_sentiment
        cursor.execute(f"""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = '{table_name}' 
            AND column_name IN ('sentiment', 'sentiment_score', 'ai_sentiment')
        """)
        sentiment_cols = [row[0] for row in cursor.fetchall()]
        
        if 'sentiment' not in sentiment_cols:
            if 'sentiment_score' in sentiment_cols:
                # Rename sentiment_score to sentiment
                cursor.execute(f"""
                    ALTER TABLE {table_name} 
                    RENAME COLUMN sentiment_score TO sentiment
                """)
            elif 'ai_sentiment' in sentiment_cols:
                # Rename ai_sentiment to sentiment
                cursor.execute(f"""
                    ALTER TABLE {table_name} 
                    RENAME COLUMN ai_sentiment TO sentiment
                """)
            else:
                # Add sentiment column if it doesn't exist
                cursor.execute(f"""
                    ALTER TABLE {table_name} 
                    ADD COLUMN sentiment VARCHAR(20)
                """)
        
        # Check and add other fields if missing
        fields_to_add = [
            ('date', 'DATE'),
            ('ai_insights', 'TEXT'),
            ('word_count', 'INTEGER DEFAULT 0'),
            ('updated_at', 'TIMESTAMP WITH TIME ZONE DEFAULT NOW()'),
        ]
        
        for field_name, field_type in fields_to_add:
            cursor.execute(f"""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = '{table_name}' 
                AND column_name = '{field_name}'
            """)
            if cursor.fetchone() is None:
                try:
                    cursor.execute(f"""
                        ALTER TABLE {table_name} 
                        ADD COLUMN {field_name} {field_type}
                    """)
                except Exception as e:
                    # Ignore errors if column already exists or other issues
                    pass


def reverse_alter_reflection_fields(apps, schema_editor):
    """Reverse: optional, can be no-op."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0005_add_coaching_os_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='goal',
            name='goals_user_id_8cf4d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='habitlog',
            name='habitlogs_user_id_77d382_idx',
        ),
        migrations.RemoveIndex(
            model_name='habitlog',
            name='habitlogs_habit_i_634629_idx',
        ),
        migrations.RenameIndex(
            model_name='goal',
            new_name='coaching_go_user_id_1907a5_idx',
            old_name='goals_user_id_49fd29_idx',
        ),
        migrations.RenameIndex(
            model_name='habit',
            new_name='coaching_ha_user_id_064770_idx',
            old_name='habits_user_id_1b4ff2_idx',
        ),
        migrations.RenameIndex(
            model_name='reflection',
            new_name='coaching_re_user_id_139e38_idx',
            old_name='reflections_user_id_601024_idx',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    remove_goal_completed_at_conditionally,
                    reverse_remove_goal_completed_at
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='goal',
                    name='completed_at',
                ),
            ]
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    remove_goal_target_date_conditionally,
                    reverse_remove_goal_target_date
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='goal',
                    name='target_date',
                ),
            ]
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    remove_habit_last_completed_at_conditionally,
                    reverse_remove_habit_last_completed_at
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='habit',
                    name='last_completed_at',
                ),
            ]
        ),
        migrations.AddField(
            model_name='habitlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aicoachmessage',
            name='context',
            field=models.CharField(blank=True, help_text='Context: habit_help, goal_revision, etc.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aicoachmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional context (habit_id, goal_id, etc.)'),
        ),
        migrations.AlterField(
            model_name='aicoachsession',
            name='prompt_count',
            field=models.IntegerField(default=0, help_text='Number of prompts in this session', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    alter_goal_fields_conditionally,
                    reverse_alter_goal_fields
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='goal',
                    name='current',
                    field=models.IntegerField(default=0, help_text='Current value toward target', validators=[django.core.validators.MinValueValidator(0)]),
                ),
                migrations.AlterField(
                    model_name='goal',
                    name='mentor_feedback',
                    field=models.TextField(blank=True, help_text='Mentor feedback (7-tier only)', null=True),
                ),
                migrations.AlterField(
                    model_name='goal',
                    name='progress',
                    field=models.IntegerField(default=0, help_text='Progress percentage 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
                ),
                migrations.AlterField(
                    model_name='goal',
                    name='status',
                    field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='active', max_length=20),
                ),
                migrations.AlterField(
                    model_name='goal',
                    name='subscription_tier',
                    field=models.CharField(blank=True, help_text='Subscription tier when goal was created', max_length=20, null=True),
                ),
                migrations.AlterField(
                    model_name='goal',
                    name='target',
                    field=models.IntegerField(help_text='Target value for progress calculation', validators=[django.core.validators.MinValueValidator(1)]),
                ),
        # Note: type field should already exist from migration 0001, but if it doesn't, 
        # we'll skip the AlterField to avoid errors
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    -- Only alter if type column exists
                    DO $$
                    BEGIN
                      IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name IN ('goals', 'coaching_goals')
                        AND column_name = 'type'
                        AND table_schema = 'public'
                      ) THEN
                        -- Column exists, no need to alter (already correct type)
                        NULL;
                      END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='goal',
                    name='type',
                    field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=20),
                ),
            ]
        ),
            ]
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Daily or weekly frequency', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='longest_streak',
            field=models.IntegerField(default=0, help_text='Longest streak achieved', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(help_text='"Learn", "Practice", "Reflect", or custom', max_length=255),
        ),
        migrations.AlterField(
            model_name='habit',
            name='streak',
            field=models.IntegerField(default=0, help_text='Current streak days', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        # Note: type field should exist from migration 0005 (renamed from category)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    -- Only alter if type column exists (or rename category to type if needed)
                    DO $$
                    DECLARE
                      table_name_var TEXT;
                    BEGIN
                      -- Find which table exists
                      SELECT table_name INTO table_name_var
                      FROM information_schema.tables 
                      WHERE table_name IN ('habits', 'coaching_habits')
                      AND table_schema = 'public'
                      LIMIT 1;
                      
                      IF table_name_var IS NOT NULL THEN
                        -- Check if type exists, if not check for category
                        IF NOT EXISTS (
                          SELECT 1 FROM information_schema.columns 
                          WHERE table_name = table_name_var
                          AND column_name = 'type'
                          AND table_schema = 'public'
                        ) THEN
                          IF EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = table_name_var
                            AND column_name = 'category'
                            AND table_schema = 'public'
                          ) THEN
                            -- Rename category to type
                            EXECUTE format('ALTER TABLE %I RENAME COLUMN category TO type', table_name_var);
                          ELSE
                            -- Add type column if neither exists
                            EXECUTE format('ALTER TABLE %I ADD COLUMN type VARCHAR(20) DEFAULT ''custom''', table_name_var);
                          END IF;
                        END IF;
                      END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='habit',
                    name='type',
                    field=models.CharField(choices=[('core', 'Core'), ('custom', 'Custom')], db_index=True, default='custom', max_length=20),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(db_index=True, help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_habit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    alter_reflection_fields_conditionally,
                    reverse_alter_reflection_fields
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='reflection',
                    name='ai_insights',
                    field=models.TextField(blank=True, help_text='AI-generated insights', null=True),
                ),
                migrations.AlterField(
                    model_name='reflection',
                    name='date',
                    field=models.DateField(db_index=True, help_text='YYYY-MM-DD'),
                ),
                migrations.AlterField(
                    model_name='reflection',
                    name='emotion_tags',
                    field=models.JSONField(blank=True, default=list, help_text='Array of emotion tags: ["overwhelmed", "confident"]'),
                ),
                migrations.AlterField(
                    model_name='reflection',
                    name='sentiment',
                    field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], help_text='User-selected or AI-computed sentiment', max_length=20, null=True),
                ),
                migrations.AlterField(
                    model_name='reflection',
                    name='user',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_reflections', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AlterField(
                    model_name='reflection',
                    name='word_count',
                    field=models.IntegerField(default=0, help_text='Word count for analytics', validators=[django.core.validators.MinValueValidator(0)]),
                ),
            ]
        ),
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together={('habit', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='reflection',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='aicoachmessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_coach_me_session_e9130d_idx'),
        ),
        migrations.AddIndex(
            model_name='aicoachmessage',
            index=models.Index(fields=['role'], name='ai_coach_me_role_0edd18_idx'),
        ),
        migrations.AddIndex(
            model_name='aicoachsession',
            index=models.Index(fields=['user', 'created_at'], name='ai_coach_se_user_id_86f8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='aicoachsession',
            index=models.Index(fields=['user', 'session_type'], name='ai_coach_se_user_id_6af19a_idx'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    -- Create index on goal.type only if type column exists
                    DO $$
                    DECLARE
                      table_name_var TEXT;
                    BEGIN
                      SELECT table_name INTO table_name_var
                      FROM information_schema.tables 
                      WHERE table_name IN ('goals', 'coaching_goals')
                      AND table_schema = 'public'
                      LIMIT 1;
                      
                      IF table_name_var IS NOT NULL THEN
                        IF EXISTS (
                          SELECT 1 FROM information_schema.columns 
                          WHERE table_name = table_name_var
                          AND column_name = 'type'
                          AND table_schema = 'public'
                        ) THEN
                          IF NOT EXISTS (
                            SELECT 1 FROM pg_indexes 
                            WHERE indexname = 'coaching_go_user_id_1ebef7_idx'
                          ) THEN
                            EXECUTE format('CREATE INDEX coaching_go_user_id_1ebef7_idx ON %I (user_id, type)', table_name_var);
                          END IF;
                        END IF;
                      END IF;
                    END $$;
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS coaching_go_user_id_1ebef7_idx;
                    """
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='goal',
                    index=models.Index(fields=['user', 'type'], name='coaching_go_user_id_1ebef7_idx'),
                ),
            ]
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'due_date'], name='coaching_go_user_id_f70fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_active'], name='coaching_ha_user_id_ef9833_idx'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    -- Create index on habit.type only if type column exists
                    DO $$
                    DECLARE
                      table_name_var TEXT;
                    BEGIN
                      SELECT table_name INTO table_name_var
                      FROM information_schema.tables 
                      WHERE table_name IN ('habits', 'coaching_habits')
                      AND table_schema = 'public'
                      LIMIT 1;
                      
                      IF table_name_var IS NOT NULL THEN
                        IF EXISTS (
                          SELECT 1 FROM information_schema.columns 
                          WHERE table_name = table_name_var
                          AND column_name = 'type'
                          AND table_schema = 'public'
                        ) THEN
                          IF NOT EXISTS (
                            SELECT 1 FROM pg_indexes 
                            WHERE indexname = 'coaching_ha_user_id_a227ea_idx'
                          ) THEN
                            EXECUTE format('CREATE INDEX coaching_ha_user_id_a227ea_idx ON %I (user_id, type)', table_name_var);
                          END IF;
                        END IF;
                      END IF;
                    END $$;
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS coaching_ha_user_id_a227ea_idx;
                    """
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='habit',
                    index=models.Index(fields=['user', 'type'], name='coaching_ha_user_id_a227ea_idx'),
                ),
            ]
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['user', 'date'], name='coaching_ha_user_id_022a38_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', 'date'], name='coaching_ha_habit_i_7fcbef_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['user', 'date', 'status'], name='coaching_ha_user_id_c51a32_idx'),
        ),
        migrations.AddIndex(
            model_name='reflection',
            index=models.Index(fields=['user', 'date'], name='coaching_re_user_id_8df0da_idx'),
        ),
        migrations.AddIndex(
            model_name='reflection',
            index=models.Index(fields=['sentiment'], name='coaching_re_sentime_fd3239_idx'),
        ),
        migrations.AlterModelTable(
            name='goal',
            table='coaching_goals',
        ),
        migrations.AlterModelTable(
            name='habit',
            table='coaching_habits',
        ),
        migrations.AlterModelTable(
            name='habitlog',
            table='coaching_habit_logs',
        ),
        migrations.AlterModelTable(
            name='reflection',
            table='coaching_reflections',
        ),
    ]
