# Generated by Django 5.2.8 on 2025-12-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0006_merge_20251220_0318'),
        ('coaching', '0006_remove_goal_goals_user_id_8cf4d7_idx_and_more'),
    ]

    operations = [
    ]
