# Generated by Django 5.2.9 on 2025-12-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0005_remove_habitlog_habitlogs_user_id_77d382_idx_and_more'),
        ('coaching', '0006_remove_goal_goals_user_id_8cf4d7_idx_and_more'),
    ]

    operations = [
        # This is a merge migration - both branches have already been applied
        # No operations needed as the database is already in the correct state
        # The state will be reconciled automatically by Django
    ]
