# Generated by Django 5.2.9 on 2025-12-20 09:15

from django.db import migrations, models


def remove_indexes_conditionally(apps, schema_editor):
    """Conditionally remove indexes only if tables exist."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Remove index from ai_coach_messages if table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_schema = 'public' AND table_name = 'ai_coach_messages'
            )
        """)
        if cursor.fetchone()[0]:
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename = 'ai_coach_messages' 
                AND indexname = 'coaching_ai_session_created_idx'
            """)
            if cursor.fetchone():
                cursor.execute("DROP INDEX IF EXISTS coaching_ai_session_created_idx")
        
        # Remove index from ai_coach_sessions if table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_schema = 'public' AND table_name = 'ai_coach_sessions'
            )
        """)
        if cursor.fetchone()[0]:
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename = 'ai_coach_sessions' 
                AND indexname = 'coaching_ai_user_session_type_idx'
            """)
            if cursor.fetchone():
                cursor.execute("DROP INDEX IF EXISTS coaching_ai_user_session_type_idx")


def reverse_remove_indexes(apps, schema_editor):
    """Reverse: no-op."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0007_merge_20251220_0856'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    remove_indexes_conditionally,
                    reverse_remove_indexes
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='aicoachmessage',
                    name='coaching_ai_session_created_idx',
                ),
                migrations.RemoveIndex(
                    model_name='aicoachsession',
                    name='coaching_ai_user_session_type_idx',
                ),
            ]
        ),
        migrations.RemoveIndex(
            model_name='habit',
            name='coaching_ha_user_id_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='habit',
            name='coaching_ha_user_id_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='habitlog',
            name='coaching_hl_user_date_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='habitlog',
            name='habitlogs_user_id_b1ad3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='habitlog',
            name='habitlogs_habit_i_fda112_idx',
        ),
        migrations.RemoveIndex(
            model_name='reflection',
            name='coaching_re_sentiment_idx',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='due_date',
        ),
        # migrations.RemoveField(
        #     model_name='habit',
        #     name='is_core',
        # ),
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together={('habit', 'date')},
        ),
        # Note: ai_sentiment and ai_tags were renamed to sentiment and emotion_tags in migration 0006
        # They should not be removed - they were renamed, not deleted
        # migrations.RemoveField(
        #     model_name='reflection',
        #     name='ai_sentiment',
        # ),
        # migrations.RemoveField(
        #     model_name='reflection',
        #     name='ai_tags',
        # ),
        # Note: response field was renamed to content in migration 0002
        # It should not be removed - it was renamed, not deleted
        # migrations.RemoveField(
        #     model_name='reflection',
        #     name='response',
        # ),
        # Note: mentor_feedback was already added conditionally in migration 0006
        # It should not be added again here - the field already exists
        # migrations.AddField(
        #     model_name='goal',
        #     name='mentor_feedback',
        #     field=models.TextField(blank=True, help_text='Mentor feedback (7-tier only)', null=True),
        # ),
        migrations.RemoveField(
            model_name='habitlog',
            name='created_at',
        ),
    ]
