# Generated by Django 5.2.9 on 2025-12-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0006_merge_20251220_0318'),
        ('coaching', '0008_remove_aicoachmessage_coaching_ai_session_created_idx_and_more'),
    ]

    operations = [
    ]
