# Generated by Django 5.2.9 on 2025-12-24 10:38

from django.db import migrations, models
from django.db.migrations import SeparateDatabaseAndState


def remove_fields_from_state_if_exist(apps, schema_editor):
    """Remove fields from state only if they exist."""
    # This is a no-op database operation - we handle DB changes in safely_remove_old_fields
    pass


def reverse_remove_fields_from_state(apps, schema_editor):
    """Reverse - no-op."""
    pass


def safely_remove_old_fields(apps, schema_editor):
    """Safely remove old fields if they exist."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check and handle ai_sentiment if it exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'coaching_reflections' 
            AND column_name = 'ai_sentiment'
            AND table_schema = 'public'
        """)
        ai_sentiment_exists = cursor.fetchone()
        
        if ai_sentiment_exists:
            # Check if sentiment column exists
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = 'coaching_reflections' 
                AND column_name = 'sentiment'
                AND table_schema = 'public'
            """)
            sentiment_exists = cursor.fetchone()
            
            if not sentiment_exists:
                # Rename ai_sentiment to sentiment
                cursor.execute("""
                    ALTER TABLE coaching_reflections 
                    RENAME COLUMN ai_sentiment TO sentiment
                """)
            else:
                # Both exist - copy data and drop ai_sentiment
                try:
                    cursor.execute("""
                        UPDATE coaching_reflections 
                        SET sentiment = ai_sentiment::text 
                        WHERE sentiment IS NULL AND ai_sentiment IS NOT NULL
                    """)
                    cursor.execute("""
                        ALTER TABLE coaching_reflections 
                        DROP COLUMN ai_sentiment
                    """)
                except Exception as e:
                    # If update fails, just drop the column
                    cursor.execute("""
                        ALTER TABLE coaching_reflections 
                        DROP COLUMN ai_sentiment
                    """)
        
        # Check and handle ai_tags if it exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'coaching_reflections' 
            AND column_name = 'ai_tags'
            AND table_schema = 'public'
        """)
        if cursor.fetchone():
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = 'coaching_reflections' 
                AND column_name = 'emotion_tags'
                AND table_schema = 'public'
            """)
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE coaching_reflections 
                    RENAME COLUMN ai_tags TO emotion_tags
                """)
            else:
                cursor.execute("""
                    ALTER TABLE coaching_reflections 
                    DROP COLUMN ai_tags
                """)
        
        # Check and handle response if it exists (should have been renamed to content)
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'coaching_reflections' 
            AND column_name = 'response'
            AND table_schema = 'public'
        """)
        if cursor.fetchone():
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = 'coaching_reflections' 
                AND column_name = 'content'
                AND table_schema = 'public'
            """)
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE coaching_reflections 
                    RENAME COLUMN response TO content
                """)
            else:
                cursor.execute("""
                    ALTER TABLE coaching_reflections 
                    DROP COLUMN response
                """)


def safely_add_goal_fields(apps, schema_editor):
    """Safely add goal fields if they don't exist."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check and add due_date if it doesn't exist
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'coaching_goals' 
            AND column_name = 'due_date'
            AND table_schema = 'public'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE coaching_goals 
                ADD COLUMN due_date DATE NULL
            """)
        
        # Check and add mentor_feedback if it doesn't exist
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'coaching_goals' 
            AND column_name = 'mentor_feedback'
            AND table_schema = 'public'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE coaching_goals 
                ADD COLUMN mentor_feedback TEXT NULL
            """)


def reverse_safely_remove_old_fields(apps, schema_editor):
    """Reverse migration - not needed."""
    pass


def reverse_safely_add_goal_fields(apps, schema_editor):
    """Reverse migration - not needed."""
    pass


class ConditionalRemoveField(migrations.RemoveField):
    """Remove field only if it exists in the migration state."""
    def state_forwards(self, app_label, state):
        try:
            model_state = state.models[(app_label, self.model_name_lower)]
            if self.name in model_state.fields:
                # Field exists, remove it
                old_field = model_state.fields.pop(self.name)
                # Also remove from indexes/constraints if needed
                for index in list(model_state.options.get('indexes', [])):
                    if hasattr(index, 'fields') and self.name in index.fields:
                        model_state.options['indexes'].remove(index)
            # If field doesn't exist, silently skip
        except KeyError:
            # Model or field doesn't exist in state, skip
            pass
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # Database operations are handled by safely_remove_old_fields RunPython
        # So we don't need to do anything here
        pass
    
    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # No-op for reverse
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0009_merge_20251221_1828'),
    ]

    operations = [
        # Handle database cleanup - remove old columns if they exist
        migrations.RunPython(
            safely_remove_old_fields,
            reverse_safely_remove_old_fields
        ),
        SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    safely_add_goal_fields,
                    reverse_safely_add_goal_fields
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='goal',
                    name='due_date',
                    field=models.DateField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='goal',
                    name='mentor_feedback',
                    field=models.TextField(blank=True, help_text='Mentor feedback (7-tier only)', null=True),
                ),
            ],
        ),
    ]
