# Generated by Django 5.2.9 on 2025-12-24 11:01

from django.db import migrations


class ConditionalRemoveField(migrations.RemoveField):
    """Remove field only if it exists in the migration state."""
    def state_forwards(self, app_label, state):
        try:
            model_state = state.models[(app_label, self.model_name_lower)]
            if self.name in model_state.fields:
                # Field exists, remove it
                old_field = model_state.fields.pop(self.name)
                # Also remove from indexes/constraints if needed
                for index in list(model_state.options.get('indexes', [])):
                    if hasattr(index, 'fields') and self.name in index.fields:
                        model_state.options['indexes'].remove(index)
            # If field doesn't exist, silently skip
        except KeyError:
            # Model or field doesn't exist in state, skip
            pass
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # Database operations already handled by migration 0010 and 0011
        # Skip database operations here
        pass
    
    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # No-op for reverse
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0011_fix_ai_sentiment_column'),
    ]

    operations = [
        # Use conditional removal - fields may not exist in state or database
        ConditionalRemoveField(
            model_name='reflection',
            name='ai_sentiment',
        ),
        ConditionalRemoveField(
            model_name='reflection',
            name='ai_tags',
        ),
        ConditionalRemoveField(
            model_name='reflection',
            name='response',
        ),
    ]
