# Generated by Django 5.2.9 on 2025-12-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0010_merge_20251223_0908'),
        ('coaching', '0012_remove_reflection_ai_sentiment_and_more'),
    ]

    operations = [
    ]
